### PR TITLE
Fix evaluateOnNewDocument sample syntax error

### PR DESCRIPTION
**Pull request by Glennvd**

### CODE REVIEW

**Review by aslushnikov — APPROVED** [review]

**Comment by aslushnikov** [comment]
@Glennvd Are you sure you signed CLA with this email? Bot's not happy.

**Comment by Glennvd** [comment]
Have done PR's before but bot never seems to be happy. Could it be because im under a corporate CLA?

**Comment by aslushnikov** [comment]
@Glennvd could be. Can you please remind me what's your company?

**Comment by Glennvd** [comment]
Agreement is signed under Social Significance LTD

**Review by ebidel — APPROVED** [review]

**Pull request merged**
