### PR TITLE
fix(Browser): fix Browser.create method - options mapping

### LINKED ISSUE #1159: ignoreHTTPSErrors is not working when request interception is on
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: ab9b34cd5dad54e170be916016a4e9b4097231ed
* Platform / OS version: debian stretch, nodejs 8.8
* URLs (if applicable): https://halva.khady.info

**What steps will reproduce the problem?**

Just launch this code to see the problem:

```javascript
// https.js
'use strict';

const puppeteer = require('puppeteer');

const URL = "https://halva.khady.info/";

(async() => {
  const args = [
    "--disable-setuid-sandbox",
    "--no-sandbox",
  ];
  const options = {
    args,
    headless: true,
    ignoreHTTPSErrors: true,
  };
  const browser = await puppeteer.launch(options);
  const page = await browser.newPage();
  await page.setRequestInterception(true);
  page.on("request", (request) => {
    if (request.resourceType === "Image") {
      request.abort();
    } else {
      request.continue();
    }
  });
  await page.goto(URL, { timeout: 8000, waitUntil: "load" });
  const html = await page.content();
  console.log(html);
  await page.close();
  await browser.close();
})();
```

**What is the expected result?**

With the request interception disabled:

```
  // await page.setRequestInterception(true);
  // page.on("request", (request) => {
  //   if (request.resourceType === "Image") {
  //     request.abort();
  //   } else {
  //     request.continue();
  //   }
  // });
```

```
$ nodejs misc/https_headless.js 
<html><head><title>potkw</title></head>
<body>
Khady Khady roule roule

</body></html>
```

**What happens instead?**

```
$ nodejs misc/https_headless.js 
(node:23556) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 8000ms exceeded
(node:23556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```

### PR DESCRIPTION
**Pull request by ghost**
**fix(Browser): fix Browser.create method - options mapping**

This patch fixes Browser.create method so that it keeps arguments naming conventions as they are passed [here](https://github.com/GoogleChrome/puppeteer/blob/cc0c461ea8ff19f856df95a7a32d24cc9b61126c/lib/Launcher.js#L137) and [here](https://github.com/GoogleChrome/puppeteer/blob/cc0c461ea8ff19f856df95a7a32d24cc9b61126c/lib/Launcher.js#L187).

_ps: this bug was introduced in #554_

### CODE REVIEW

**Comment by ghost** [comment]
I signed it!

**Comment by aslushnikov** [comment]
@octasimo Thanks, the PR is good, though I don't think it fixes any of the mentioned bugs.

**Comment by ghost** [comment]
I think you're right, I'll amend the pr description.

**Review by aslushnikov — APPROVED** [review]
Great, thanks

**Pull request merged**
