### PR TITLE
fix(Launcher): do not detach child process on windows

### LINKED ISSUE #2053: Allow Chromium process "detached" argument to be configurable?
Is there any special reason why Chromium process is spawned with "detached:true" argument? Can it be configurable? I have a situation on windows platform when i am creating child processes which are launching puppeteer instances. When i kill child processes, Chromium instances remain (on windows signal SIGTERM is not supported ... ). Is this a preferable solution or something else?

### PR DESCRIPTION
**Pull request by aslushnikov**
Fixes #2053.

### CODE REVIEW

**Comment by aslushnikov** [comment]
@alixaxel @JoelEinbinder can you guys please check if this works for you on win? Process management is not a well-tested area of ours.

**Comment by alixaxel** [comment]
@aslushnikov I'm not a windows user.

**Comment by aslushnikov** [comment]
@alixaxel oops, sorry for the noize.
cc @vsemozhetbyt

**Comment by vsemozhetbyt** [comment]
@aslushnikov Can you provide some code I could test on Windows to be sure this fix the issue?

**Comment by aslushnikov** [comment]
@vsemozhetbyt Try running the following script and then terminate running node.js program differently:
- via taskmanager
- via Ctrl-C
- via closing the terminal

In all the cases, the spawned chromium instance should be closed. 

```js
var pptr = require('puppeteer');
(async() => {
  const browser = await pptr.launch();
  console.log('Launched!');
})();
```

**Comment by vsemozhetbyt** [comment]
@aslushnikov I can confirm that with this patch all three terminations of the running node.js program also close the spawned chromium instance on Windows 7 x64 with the `cmd.exe` shell.

**Comment by aslushnikov** [comment]
@vsemozhetbyt: Thank you.

@JoelEinbinder, let's merge this?

**Comment by aslushnikov** [comment]
@vsemozhetbyt: Thank you.

@JoelEinbinder, let's merge this?

**Comment by JoelEinbinder** [comment]
I still get some errors when closing things on windows, but it actually closes things now so I'd say this is better.

**Review by JoelEinbinder — APPROVED** [review]

**Pull request merged**
