### PR TITLE
chore: mark version v3.0.0

### PR DESCRIPTION
**Pull request by hanselfmu**

### CODE REVIEW

**Review by mathiasbynens — APPROVED** [review]

**Comment by mathiasbynens** [comment]
This LGTM, but we’ll probably want to merge your Node.js PR, then @mjzffr’s patch, _and_ land a Chromium roll first.

**Comment by hanselfmu** [comment]
I was going to merge this first, and rebase other PRs on top of it and merge them, but your plan actually sounds easier.

For Chromium roll, I can definitely roll a new version in, but it seems like it won't be Chrome 81 yet. The latest stable is 80.0.3987.132.

**Comment by hanselfmu** [comment]
It seems like Chromium 81 will be released on March 17th. I'll wait on 81 to be released and roll that version in.

**Comment by mjzffr** [comment]
> It seems like Chromium 81 will be released on March 17th. I'll wait on 81 to be released and roll that version in.

^ /cc @digitarald

**Comment by hanselfmu** [comment]
Since M81 stable release has been delayed until further notice, I will roll the newest M80 in the next few days, which is released today, and publish 3.0.0.

**Comment by hanselfmu** [comment]
It seems like Chromium don't publish snapshots for versions other than X.Y.Z.0, so will skip rolling a new Chromium in for 3.0.0.

**Comment by AviVahl** [comment]
Chrome 81.0.4044.92 is out: https://chromereleases.googleblog.com/2020/04/stable-channel-update-for-desktop_7.html

**Pull request closed without merging**
