### PR TITLE
feat: getFrame for ElementHandle

### PR DESCRIPTION
**Pull request by schelkun**
Closes https://github.com/GoogleChrome/puppeteer/issues/433

### CODE REVIEW

**Comment by schelkun** [comment]
Oh nice, problems with googlebot.
How can I submit smth without bureaucracy?

**Comment by schelkun** [comment]
So I should:

- delete my fork;
- create new fork;
- commit again, but via GitHub interface;
- delete this PR;
- create new PR.

For glory of googlebot of course!

I don't have enough time for this, so please check is my solution works?
And maybe I will recreate this later or somebody else will create an PR.

**Comment by vsemozhetbyt** [comment]
@schelkun You can try this in your local branch:
```console
git commit --amend --author="Schelkun <email@for_github>"
git push --force-with-lease
```

**Comment by JoelEinbinder** [comment]
With #1972, I think you can just do `elementHandle.executionContext().frame()`.

**Comment by schelkun** [comment]
@JoelEinbinder so this PR is useless?

**Comment by schelkun** [comment]
@JoelEinbinder thanks for this solution.

**Comment by schelkun** [comment]
@JoelEinbinder just checked, your solution does not work

**Comment by ohana54** [comment]
@JoelEinbinder likewise, looks like the execution context for the iframe element is the execution context of the page containing the iframe, not for the frame itself.
@schelkun can you please reopen this?

**Pull request closed without merging**
