### PR TITLE
feat(page): add omitBackground option for page.pdf method

### PR DESCRIPTION
**Pull request by d-buckner**
Adds `omitBackground` option for Page.pdf to allow for transparent backgrounds. This option is available in the screenshot api, this change unifies this for both `.screenshot` and `.pdf`.

Related issues: #6906  #2545

### CODE REVIEW

**Comment by d-buckner** [comment]
@googlebot I signed it!

**Review by jschfflr — CHANGES_REQUESTED** [review]
Hi d-rowe, thanks for your contribution! 
Your changes look good to me but it would be great if you could add a test for them.
I'm not sure how stable the pdf output is so maybe you can try testing it with golden snapshots (take a look at the screenshot tests to see how) and if that doesn't work we can find another way to at least have basic test coverage.
Thanks!

**Comment by d-buckner** [comment]
Thanks. Looks like the tests are only setup to compare pngs. Any suggestions for alternative ways to get some basic test coverage?

**Comment by jschfflr** [comment]
Well if that's not currently set up to handle PDFs, I think we can skip it for now. 
But maybe you can create a tracking bug for this on this repository so that we can take a look at it in the future.
Please also link to this pull request from that new issue. Thanks!

**Review by jschfflr — APPROVED** [review]

**Pull request merged**
