### PR TITLE
docs: clarify the waitForXPath return type (#9541)

### PR DESCRIPTION
**Pull request by Rafael-Martins**
**What kind of change does this PR introduce?**

test & docs

**Did you add tests for your changes?**
yes

**Summary**

Adds more description to `waitForXPath` and add more tests as well. Related to: [#9541](https://github.com/puppeteer/puppeteer/issues/9541)

### CODE REVIEW

**Comment by Rafael-Martins** [comment]
I brought some discussion about this type [here](https://github.com/puppeteer/puppeteer/issues/9541#issuecomment-1404266812)

**Review by OrKoN — CHANGES_REQUESTED** [review]
Could you please run `npm run docs` to regenerate the docs?

**Review by OrKoN — CHANGES_REQUESTED** [review]
Could you please add a test similar to the test called `hidden should wait for display: none` that verifies that hidden: true always returns null. I did a quick check and it looks like we do return element handle.

**Comment by Rafael-Martins** [comment]
> Could you please add a test similar to the test called `hidden should wait for display: none` that verifies that hidden: true always returns null. I did a quick check and it looks like we do return element handle.

I wrote some tests and it seems to be returning null just if the element is not found at the beginning, if the element has found and became hidden it returns a empty object.

This function should always return null `(when hidden: true)`? even in the second situation?

And for now, just testing the first situation is fine?

**Comment by OrKoN** [comment]
I think if we ever return an ElementHandle value with hidden: true, we cannot change the types here.

**Comment by OrKoN** [comment]
I think the documentation might be outdated here? perhaps we should clarify the behaviour better in the documentation.

**Comment by Rafael-Martins** [comment]
> I think the documentation might be outdated here? perhaps we should clarify the behaviour better in the documentation.

It appears to be the case from my perspective :thinking:

I believe the test I added is beneficial and reflective of the current behavior, and can be kept in place. Is it preferred that I revert the type changes and enhance the documentation?

**Comment by OrKoN** [comment]
Yes, let's keep the test and update the documentation. Perhaps we can extend the test to also demonstrate non-null value with hidden: true when the element becomes hidden in the middle of the call.

**Review by OrKoN — APPROVED** [review]

**Pull request merged**
