### PR TITLE
Revert removal of shared TaskQueue for `page.screenshot()`

### PR DESCRIPTION
**Pull request by dmitrysteblyuk**
Issue https://github.com/puppeteer/puppeteer/issues/6713.
Please, notice that I changed the return type of `page.screenshot()` back to `Promise<Buffer | string>`.
I did it because I couldn't find any place where it returns `void`.
Let me know if it was a mistake on my part, I'll change it back.

### CODE REVIEW

**Comment by dmitrysteblyuk** [comment]
@jackfranklin sorry for the ping, but Travis appears not to be working for the last 5 days.

**Comment by mathiasbynens** [comment]
> @jackfranklin sorry for the ping, but Travis appears not to be working for the last 5 days.

Yeah, we're aware of this. Travis essentially removed support for their free plan, so we'll have to migrate to GitHub Actions. #6726

**Comment by jackfranklin** [comment]
@dmitrysteblyuk thank you for this PR and for the bug report. This looks good to me. Now we've landed GitHub actions into the codebase, would you mind rebasing your PR? Then we can see if CI is happy 👍

**Comment by jackfranklin** [comment]
@mathiasbynens PTAL.

**Review by jschfflr — APPROVED** [review]

**Comment by jschfflr** [comment]
@googlebot I consent.

**Pull request merged**
