### PR TITLE
test: add a test for ctrlKey on wheel 

### LINKED ISSUE #12093: [Bug]: (Firefox) Wheel event doesn't have ctrlKey set to true when Control key is down
### Minimal, reproducible example

```TypeScript
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    product: "firefox",
    headless: true,
    protocol: "webDriverBiDi",
  });

  const data = "data:text/html,<script>window.ctrlKey = false; window.addEventListener('wheel', e => { window.ctrlKey = e.ctrlKey; });</script>";
  const page = await browser.newPage();

  await page.goto(data);

  await page.keyboard.down("Control");
  await page.mouse.wheel({ deltaY: -100 });
  await page.keyboard.up("Control");

  const ctrlKey = await page.evaluate(() => window.ctrlKey);
  if (!ctrlKey) {
    throw new Error("Control key was not pressed");
  }

  await page.close();
  await browser.close();
})();
```

### Error string

Control key was not pressed

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

_No response_

### Expectation

ctrlKey property of the wheel event must be `true`.

### Reality

It's `false`.

### Puppeteer configuration file (if used)

_No response_

### Puppeteer version

22.4.1

### Node version

18.19.1

### Package manager

npm

### Package manager version

10.2.4

### Operating system

Windows

### PR DESCRIPTION
**Pull request by OrKoN**
Closes #12093

### CODE REVIEW

**Review by sadym-chromium — APPROVED** [review]

**Comment by lutien** [comment]
To avoid problem with zoom, you could also use another key, in wpt tests we used shift, for example.

**Comment by whimboo** [comment]
I investigated the issue with @OrKoN on Matrix. So yes we need to set this pref by default for the Remote Agent. @OrKoN will file a bug for it.

Maybe we can wait with landing this patch until we have fixed it in Firefox? Then we don't have to set it explicitly before starting Firefox.

**Comment by OrKoN** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1901211

**Comment by OrKoN** [comment]
> I investigated the issue with @OrKoN on Matrix. So yes we need to set this pref by default for the Remote Agent. @OrKoN will file a bug for it.
> 
> Maybe we can wait with landing this patch until we have fixed it in Firefox? Then we don't have to set it explicitly before starting Firefox.

I have updated the patch to work around the issue in a different way. Once https://bugzilla.mozilla.org/show_bug.cgi?id=1901211 and the setting is changed in the remote agent, we can update the test.

**Pull request merged**
