### PR TITLE
Fixed console log example

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by niftylettuce** [comment]
Actually this is wrong, it should simply be `console.log(message)` I believe?

**Comment by JoelEinbinder** [comment]
I think it would be:
```js
page.on('console', ...args => {
  for (let i = 0; i < args.length; ++i)
    console.log(`${i}: ${args[i]}`);
});
```
but I'm not super familiar with the new console api.

**Review by aslushnikov — APPROVED** [review]
Thanks!

**Review by aslushnikov — CHANGES_REQUESTED** [review]
Oh wait, i think the current code is actually correct - no need for pr

**Review by aslushnikov — APPROVED** [review]
Actually, a good change, I got confused. Please, sign the CLA, and it's good to go!

**Comment by niftylettuce** [comment]
Not interested in signing it

**Comment by aslushnikov** [comment]
@niftylettuce without CLA I can't merge this in.

**Comment by niftylettuce** [comment]
The GitHub standard is that with any commits you push towards a repo you are obviously adhering to the `LICENSE` that already exists.  This is ridiculous to expect.  It's 2017- you should do everything you can to welcome contributions, not push them away.

**Comment by niftylettuce** [comment]
This legal junk https://cla.developers.google.com/clas/new?domain=DOMAIN_GOOGLE&kind=KIND_INDIVIDUAL is just as bad as the Facebook React BSD license.

**Comment by niftylettuce** [comment]
Yeah I'll sign a huge legal document just so I can help fix typos and improve docs... yeah right.  Good luck!

**Pull request closed without merging**
