### PR TITLE
fix(Page): fix page.goto to return Response when page pushes new state

### LINKED ISSUE #2411: Page.goto returns null for some URLs since version 1.3.0
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.3.0
* Platform / OS version: Mac OSX
* Node.js version: v7.10.1 / v9.8.0
* URLs (if applicable):
  * https://remarkjs.com/
  * http://lab.hakim.se/reveal-js
  * https://leaverou.github.io/csss/
  * http://artificer.jboss.org/slides/general/opensource-getting-involved.html
  * http://joshbode.github.io/remark/ansi.html

**What steps will reproduce the problem?**

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  response = await page.goto('https://remarkjs.com/');

  console.log('response:', response)

  await browser.close();
})();
```

For the URLs listed above.

**What is the expected result?**

`response` should not be null.

**What happens instead?**

`response` is null. Note that it works with Puppeteer version 1.2.0.

### PR DESCRIPTION
**Pull request by aslushnikov**
Fixes #2411.

### CODE REVIEW

**Review by JoelEinbinder — APPROVED** [review]
Makes sense.

**Comment by ntzm** [comment]
Does this also fix #2479 @aslushnikov?

**Comment by aslushnikov** [comment]
@ntzm it doesn't.

**Comment by ntzm** [comment]
No worries, thanks for all your hard work!

**Pull request merged**
