### PR TITLE
chore: remove search.js example

### LINKED ISSUE #1557: Example: search.js should demo something other than google.com

### PR DESCRIPTION
**Pull request by aslushnikov**
The example is violating the TOS of google.com

Fix #1557

### CODE REVIEW

**Review by JoelEinbinder — APPROVED** [review]

**Comment by ebidel** [comment]
LGTM. I was thinking we'd just replace the demo with something similar that shows grabbing page content. This example is also nice b/c it shows a couple of the APIs together (keyboard input and click).

**Review by ebidel — APPROVED** [review]

**Comment by aslushnikov** [comment]
@ebidel yeah we'll probably make another one with our own protocol viewer

**Comment by schelkun** [comment]
What about DuckDuckGo?

**Comment by ebidel** [comment]
https://chromedevtools.github.io/devtools-protocol/ is the protocol viewer @aslushnikov is referring to. I think it's probably safer to use that for an example than a site that our team does not maintain. It has an input with search results...so it would be very similar to the original demo.

**Pull request merged**
