### PR TITLE
feat(browser): see if chrome process is currently open

### PR DESCRIPTION
**Pull request by ShragaUser**
Exposing a function on browser instance to see if Chrome process is currently open.

This feature addresses ISSUE #3149

This is actually my first time contributing to an open source program.
so i would love your help with anything here.

thank you! 👍

### CODE REVIEW

**Comment by ShragaUser** [comment]
@googlebot  i signed it

**Comment by ShragaUser** [comment]
@aslushnikov - Hi! for some reason the continuous-integration/appveyor/pr is failing with this error: 
`ERR! request to https://registry.npmjs.org/extract-zip failed, reason: Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"`

im pretty sure that this isnt because of changes in my code. 
I would really appreciate it if you could help me with this issue as im very new to this whole process. 

thank you!

**Comment by vsemozhetbyt** [comment]
It seems this is an `npm` issue: see the last issues in https://npm.community/c/bugs

**Comment by ShragaUser** [comment]
@vsemozhetbyt - oh I see. Does that mean we can maybe go forward with the pr without that check being passed?

**Comment by ShragaUser** [comment]
seems like the npm bug that failed the appveyor CI was resolved and now everything works as expected! 🥇

**Comment by aslushnikov** [comment]
> This is actually my first time contributing to an open source program.

Hey @ShragaUser, yay! :) It's nice to have more of us here!

> This feature addresses ISSUE #3149

You've actually suggested a nice solution for the issue that doesn't require any new API additions. There's no need to land this anymore.

P.S. Thank you for participation and for helping us out!

**Pull request closed without merging**
