### PR TITLE
fix(page): page.waitForFunction should work with multiline strings

### LINKED ISSUE #3723: page.waitForFunction fails because of whitespace
### Steps to reproduce
```
await page.waitForFunction(`
  (() => true)()`);
```
never returns, but

```
await page.waitForFunction(`(() => true)()`);
```
does. I expect them both to return immediately.

**Tell us about your environment:**

* Puppeteer version: 1.11.0
* Platform / OS version: MacOS
* URLs (if applicable):
* Node.js version: 8.9.1

### PR DESCRIPTION
**Pull request by fringd**

### CODE REVIEW

**Comment by fringd** [comment]
I'm not sure why the pr title lint is stuck :/

**Comment by aslushnikov** [comment]
@fringd can you please add a test to [`//test/evaluation.spec.js`](https://github.com/GoogleChrome/puppeteer/blob/master/test/evaluation.spec.js)?

**Review by aslushnikov — APPROVED** [review]
Let's merge this - I'll add a test in a follow-up

**Comment by fringd** [comment]
thanks! I'm super sick this week. thanks for writing the test ^_^

**Comment by aslushnikov** [comment]
@fringd get well soon!

**Pull request merged**
