### PR TITLE
add page navigation load handlers to setContent

### LINKED ISSUE #728: Page.setContent should wait for resources to be loaded
(as mentioned in #486 and other places)

We need a way to wait for page to load all the resources after the `page.setContent`.

The [lifecycle events](https://aslushnikov.github.io/vanilla-protocol-viewer/#Page.lifecycleEvent) might help help.

### PR DESCRIPTION
**Pull request by devsnek**
this should allow doing stuff like `setContent('...', { waitUntil: 'networkidle' })`

closes #728

### CODE REVIEW

**Comment by devsnek** [comment]
I signed it!

**Comment by aslushnikov** [comment]
Hi @devsnek, thanks for the PR.

Waiting for network idle is currently supported, like this:

```js
await Promise.all([
  page.setContent('...'),
  page.waitForNavigation({waitUntil: 'networkidle'})
]);
```

However, this would not work if `setContent` doesn't instantiate any new requests.
We have some on-going work to support life cycle events that should help to fix #728.

**Comment by devsnek** [comment]
awesome, should I close this then?

**Comment by aslushnikov** [comment]
@devsnek I'll close this for you :)

**Comment by BkSouX** [comment]
Hi @aslushnikov 

I'm sorry if I should not comment a closed PR, I'll create a ticket if needed.
What is the difference between

```javascript
await Promise.all([
  page.setContent('...'),
  page.waitForNavigation({waitUntil: 'networkidle'})
]);
```

and 

```javascript
await  page.setContent('...');
await  page.waitForNavigation({waitUntil: 'networkidle'});
```

Thank you

**Comment by devsnek** [comment]
the bottom one is more likely to get stuck with the current lifecycle because of race conditions with network requests

**Pull request closed without merging**
