### PR TITLE
chore: update protocol.d.ts

### PR DESCRIPTION
**Pull request by jackfranklin**
The result of `npm run update-protocol-d-ts`

### CODE REVIEW

**Review by mathiasbynens — APPROVED** [review]

**Comment by mathiasbynens** [comment]
Should we enforce this on prepublish (or pre-commit, with git hooks)?

**Comment by jackfranklin** [comment]
> Should we enforce this on prepublish (or pre-commit, with git hooks)?

Yeah, I was just thinking similar. Maybe a CI task that runs the generator and compares ? And errors if they are different? 

My thinking of it being on CI is then people don't pay the cost on every commit. WDYT?

**Comment by jackfranklin** [comment]
@mathiasbynens I'm going to merge this as it's blocking my work on a TS migration but let me know what your thoughts are on how best to enforce this.

**Comment by mathiasbynens** [comment]
> My thinking of it being on CI is then people don't pay the cost on every commit. WDYT?

SGTM.

**Pull request merged**
