### PR TITLE
fix: make screenshots work in the web

### PR DESCRIPTION
**Pull request by joelgriffith**
On web, the `fs` module is always imported when doing screenshots wo a path. This PR addresses that by reworking the flow of condition checks. Open to nitpicks, and thanks!

### CODE REVIEW

**Review by mathiasbynens — APPROVED** [review]

**Comment by joelgriffith** [comment]
@jackfranklin wondering if you could take a quick peak at this. Just a quick conditional change.

**Comment by joelgriffith** [comment]
Been a few weeks, would filing a bug help get this more notice?

**Review by jackfranklin — APPROVED** [review]
LGTM, thanks! Apologies for the slow review.

**Comment by joelgriffith** [comment]
Thanks!

**Pull request merged**
