### PR TITLE
Bump version to 0.10.2-alpha

### PR DESCRIPTION
**Pull request by aslushnikov**

### CODE REVIEW

**Review by JoelEinbinder — APPROVED** [review]

**Comment by pocketjoso** [comment]
@aslushnikov I would like to test these changes, especially #565 - could you publish this version to npm? as under `alpha`, `next` or similar tag..

**Comment by aslushnikov** [comment]
@pocketjoso the suggested way to try tip-of-tree is to install from github: `npm install GoogleChrome/puppeteer`. Do you have any concerns about it?

**Comment by pocketjoso** [comment]
@aslushnikov I use `yarn` and usually it doesn't work well with yarn to install from github. I'll try it..

**Comment by pocketjoso** [comment]
Okay not sure what the difference is, but so far this worked for me with yarn as well, so for now I'm good. 👍

**Comment by pocketjoso** [comment]
#565 btw is an absolute blocker for me to use `puppeteer` in production - do you have any ETA for the next stable release?

**Comment by aslushnikov** [comment]
@pocketjoso should be sometime this week

**Pull request merged**
