### PR TITLE
refactor: merge various connect and launch option types

### PR DESCRIPTION
**Pull request by OrKoN**
Technically, it could be a breaking change since the types are slightly different but the functionality is still the same and the new types are a superset of the previous scattered types. Old types are made aliases to the new types and deprecated.

### CODE REVIEW

**Review by Lightning00Blade — APPROVED** [review]
LGTM, but would consider adding the older names as alias export so we don't brake builds of anyone that is using them, WDYT? Then we remove them in v24

**Review by Lightning00Blade — APPROVED** [review]
LGTM, added it to the list for v24

**Comment by lameuler** [comment]
this seems to missing the type alias for `PuppeteerLaunchOptions` which has been replaced by the new `LaunchOptions`? so could cause some issues especially since this change doesn't show up in the changelog

**Comment by OrKoN** [comment]
Thanks! Indeed I overlooked PuppeteerLaunchOptions. https://github.com/puppeteer/puppeteer/pull/13376 should fix this

**Pull request merged**
