### PR TITLE
Launcher: disable extensions and google translate by default

### PR DESCRIPTION
**Pull request by aslushnikov**
This patch teaches `puppeteer.launch` to run chromium with disabled
chrome extensions and google translate services.

References #760

### CODE REVIEW

**Review by ebidel — APPROVED** [review]

**Comment by aslushnikov** [comment]
@ebidel it turned out I don't really know why we want this in. Why would we want this?

**Comment by ebidel** [comment]
Keep the launched chrome slimmer? Not sure it adds a ton of value for us. Turning these off makes more sense for Lighthouse where we're reusing an existing install of chrome.

**Comment by aslushnikov** [comment]
I slept with this and now I like the patch since it aligns headful/headless with each other.
@JoelEinbinder any concerns?

**Review by JoelEinbinder — APPROVED** [review]

**Comment by cretz** [comment]
@aslushnikov , @JoelEinbinder, et al - Sadly creating and merging this has disabled everyone's ability to automate with extensions in non-headless mode. Is there any way to work around this, or are these "default" args more like "permanent unchangeable" args?

**Comment by aslushnikov** [comment]
@cretz @JoelEinbinder is working on a patch to override default arguments. Filed #872 to track progress.

**Pull request merged**
