### PR TITLE
fix: make chromium-bidi an opt peer dep

### LINKED ISSUE #9665: [Bug]: package managers now give warning about unmet peer dependency `mitt`
### Bug expectation

**Expected**
No warnings when add puppeteer to my project

**Actual**
pnpm, yarn and npm give a warning about unmet peer dependency `mitt`

> ??? puppeteer
  ??? puppeteer-core
    ??? chromium-bidi
      ??? ? missing peer mitt@"*"
Peer dependencies that should be installed:
  mitt@"*"

Are we now supposed to include `mitt` every place where we use `puppeteer`?

### Bug behavior
had to check one to see if the bot is happy
- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```ts
import puppeteer from 'puppeteer'
```

### Error string

missing peer mitt@"*"

### Puppeteer configuration

_No response_

### Puppeteer version

19.7.0

### Node version

14.19.0

### Package manager

npm

### Package manager version

9.4.2

### Operating system

Linux

### PR DESCRIPTION
**Pull request by OrKoN**
Closes #9665

### CODE REVIEW

**Review by Lightning00Blade — APPROVED** [review]

**Comment by karlhorky** [comment]
Seems like this broke the build for some people (we are also having problems with `esbuild` with a missing `chromium-bidi` dependency):

- https://github.com/puppeteer/puppeteer/issues/9665#issuecomment-1433385630

**Comment by OrKoN** [comment]
@karlhorky I believe this has been already fixed.

**Comment by OrKoN** [comment]
@karlhorky see https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v19.7.2 Please open an issue if you experience an issue with the latest version.

**Comment by karlhorky** [comment]
Ah ok, maybe this was released in [`puppeteer-core@v19.7.2`](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v19.7.2), upgrading now.

**Comment by karlhorky** [comment]
Confirmed, [`puppeteer-core@v19.7.2`](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v19.7.2) fixes the issue, thanks! 🙌

**Pull request merged**
