### PR TITLE
feat(coverage): option for raw V8 script coverage

### PR DESCRIPTION
**Pull request by Quramy**
### What I did

- Add `includeRawScriptCoverage` option to include full V8 precise coverage entry to result of `page.coverage.stopJSCoverage()`

### Motivation
It's related to issue #985 . I want to map Puppeteer's coverage result with source-map with https://github.com/istanbuljs/v8-to-istanbul . But The Puppeteer's coverage result's range objects are edited by `convertToDisjointRanges` function and v8-to-istanbul can't map .
So, I want this option to get V8 raw coverage result, whose functions' ranges are not joined.

[FYI] The similar method in Praywrite returns raw V8 coverage result. https://playwright.dev/#version=v1.4.2&path=docs%2Fapi.md&q=chromiumcoveragestopjscoverage

### CODE REVIEW

**Comment by Quramy** [comment]
~~hmmm, `extra test` CI job was failed. 🤔  Tell me how to fix it ?~~

**Review by jackfranklin — APPROVED** [review]
Thank you for the PR! This LGTM.

@mathiasbynens wdyt?

**Comment by Quramy** [comment]
@mathiasbynens @jackfranklin  Can you please merge this?

**Comment by Quramy** [comment]
How about this? Let me know if anything needs to be fixed !

**Review by jschfflr — APPROVED** [review]
This change looks good to me!

**Pull request merged**
