### PR TITLE
fix: strip trailing slashes from downloadBaseUrl

### PR DESCRIPTION
**Pull request by paulmilbank**
**What kind of change does this PR introduce?**
feature

**Did you add tests for your changes?**
No, happy to do this, but unsure of the best place to add this

**If relevant, did you update the documentation?**
No, this shouldn't need a documentation update

**Summary**
https://github.com/puppeteer/puppeteer/issues/12861
I encountered an issue with the download url getting a 404 when setting `PUPPETEER_DOWNLOAD_BASE_URL` to `https://storage.googleapis.com/chrome-for-testing-public/` per a comment on an issue in the Puppeteer repo.
@puppeteer/browsers expects the url to not have a trailing `/`
I thought it might be useful to strip trailing slashes off so the URL is in the expected format.

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

**Comment by paulmilbank** [comment]
This may be the wrong place to put this. I'm guessing that we want to retain the `string |  undefined` type and not coerce it to a string here so that the default baseUrl parameters in the browsers package take precedence. Possibly if this is useful, it should be implemented in the browsers package in the `resolveDownloadUrl` functions.

**Review by OrKoN — COMMENTED** [review]
Thanks for the PR. Could you please run `npm run format`?

**Comment by Lightning00Blade** [comment]
I am not sure if we should make this changes as `example.com/A/B//C` and `example.com//A/B/C` are both valid URLs.
And any URL with path that contains 2 slashes next to each other.
Internally we convert the string to `URL` object so that makes the verification process. 
Maybe a note on the documentation would be a better suited for this rather than changing the behavior.
@OrKoN WDYT?

**Comment by OrKoN** [comment]
I think it makes sense. Let's leave it as is and document that we will append a value starting with `/` to the base URL.

**Comment by Lightning00Blade** [comment]
Closing per last comment will keep track on the issue.

**Pull request closed without merging**
