### PR TITLE
test(ng-schematics): smoke tests fixed for local running

### PR DESCRIPTION
**Pull request by Riyazul555**
**What kind of change does this PR introduce?**

Error Handling:

Wrapped the main logic in an async function (runSmokeTests) and added a .catch block to handle any uncaught exceptions. This ensures any errors are logged, and the process exits with a failure code.
Initialization:

Ensured that the script initializes and installs dependencies correctly in the CI environment.
Await in Loop:

Used a regular for loop instead of for await for iterating through runnerGroup to keep consistency and avoid issues.

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**
Closes Issue #12619

### CODE REVIEW

**Comment by Riyazul555** [comment]
@OrKoN please checkout This PR
if any changes are required do tell me 
Thanks

**Comment by OrKoN** [comment]
@Riyazul555 please sign the CLA so that the CLA check passes

**Comment by Riyazul555** [comment]
Hey @OrKoN can you please tell me how to sign the CLA pass ?
Thanks

**Comment by OrKoN** [comment]
@Riyazul555 you can follow the instructions from the check posted above https://github.com/puppeteer/puppeteer/pull/12687/checks?check_run_id=26852656282

**Comment by Riyazul555** [comment]
I rescanned the CLA @OrKoN 
Please see it

**Comment by OrKoN** [comment]
I think it still not detected

**Comment by Riyazul555** [comment]
What to do next @OrKoN ?

**Comment by Riyazul555** [comment]
@OrKoN any updates ?

**Comment by Lightning00Blade** [comment]
Supersede by #12711.

**Pull request closed without merging**
