### PR TITLE
chore(docs): update `troubleshooting.md`

### PR DESCRIPTION
**Pull request by crisanmm**
Fix `configuration` link

### CODE REVIEW

**Comment by Lightning00Blade** [comment]
Hey, @crisanmm I tried it out and it works as expected for me, so I will be closing this one. If the issue is persistent please try incognito and give more detail on which platform and what browser this is observed.

**Comment by crisanmm** [comment]
> Hey, @crisanmm I tried it out and it works as expected for me, so I will be closing this one. If the issue is persistent please try incognito and give more detail on which platform and what browser this is observed on.

Sure, I tested this on

macOS 13.1:
* Chrome 110
* Safari 16.2
* Firefox 109

and iOS 16.1 safari,

All of the above redirect to this 404 page:
SCR-20230313-oken


IMO this seems more of how github handles redirects, so in this scenario https://github.com/puppeteer/puppeteer/blob/main/docs/guides/configuration is not redirected to https://github.com/puppeteer/puppeteer/blob/main/docs/guides/configuration.mdx.
I feel like this issue could also be solved by renaming `/docs/guides/configuration.mdx` to `/docs/guides/configuration.md`.

**Comment by Lightning00Blade** [comment]
I see what is going on. You are using the GitHub File UI to navigate though docs. I don't think we will fix this as we use those files to build [pptr.dev](https://pptr.dev/) and that will brake it.

**Comment by crisanmm** [comment]
I understand. I got on the github page by navigating from a google search result, I'll just use the [pptr.dev](https://pptr.dev/) instead. Thanks for clearing it up!

**Pull request closed without merging**
