### PR TITLE
fix: increase commit header length limit

### PR DESCRIPTION
**Pull request by OrKoN**
https://github.com/puppeteer/puppeteer/commit/04f7659f9adae7415bfea3f538a446c624d852e8 hit the limit but I don't see a reason why we need to be so strict. Increasing the limit to 120 chars.

### CODE REVIEW

**Comment by ergunsh** [comment]
AFAIU GitHub cuts of the commit to other line when it is longer than 72 characters. So, AFAIU again, that's why the default limit is 72 characters. IMO, it might make sense to keep it in 72 characters to not allow this behavior.

Additional info can be written in other lines, wdyt?

**Comment by OrKoN** [comment]
The limit already was 100. Also, GitHub cutting off lines is not a big problem as you can see the rest on the next line.

**Comment by OrKoN** [comment]
Alternatively, I can fix that commit with a force push :)

**Comment by OrKoN** [comment]
Let me just do that, I think.

**Comment by ergunsh** [comment]
Oh I see, I tried to understand why it was 100 in the first place and it seems like 72 could cause issues with automatic PRs (example https://github.com/conventional-changelog/commitlint/issues/859)

I'm fine with both options now, thank you :)

**Comment by OrKoN** [comment]
Oh, thanks for digging! yeah, I think 72 is too low for most of typical commit messages.

**Pull request closed without merging**
