### PR TITLE
docs(new): migrate TimeoutError to TSDoc

### PR DESCRIPTION
**Pull request by OrKoN**

### CODE REVIEW

**Comment by OrKoN** [comment]
@jackfranklin it looks like the tests fail? Did I do something wrong here?

**Comment by OrKoN** [comment]
It looks like CI is using api-documenter 7.8.13  and my local version after npm install is 7.8.12

**Comment by jackfranklin** [comment]
> It looks like CI is using api-documenter 7.8.13 and my local version after npm install is 7.8.12

Ah, we should probably hard pin this dependency to make sure there are no output differences locally vs CI. I'll do that in a PR now and that should resolve this.

**Comment by jackfranklin** [comment]
https://github.com/puppeteer/puppeteer/pull/6063 should enable this to go green!

**Review by jackfranklin — APPROVED** [review]

**Pull request merged**
