### PR TITLE
Add Jest test example

### PR DESCRIPTION
**Pull request by trevordmiller**
fyi @cpojer

### CODE REVIEW

**Comment by trevordmiller** [comment]
I signed it!

**Comment by trevordmiller** [comment]
My only problem with this approach is that the debugging options don't launch non-headless Chrome when running through Jest; ie:

```
const browser = await puppeteer.launch({
  headless: false,
  slowMo: 250 // slow down by 250ms
});
```

@cpojer, any idea how to get that working?

**Comment by aslushnikov** [comment]
Hey @trevordmiller,

Why do you want this to be part of puppeteer rather then jest?

**Comment by trevordmiller** [comment]
@aslushnikov I thought it could be helpful to have some examples of using puppeteer for end-to-end tests; but if that's not what the `examples/` directory is for then we can close this :)

**Comment by JoelEinbinder** [comment]
This looks pretty straight forward from a Jest perspective. I'd like to avoid having an example for every different testing library in this project. The debugging story with Jest is interesting. If there is something we can do to make that smoother feel free to file an issue.

**Pull request closed without merging**
