### PR TITLE
Add 'allCookies' method

### PR DESCRIPTION
**Pull request by MicheleLevorato**
This method returns all the cookies for the current page, even third party ones.
Based on the Chromium command Network.getAllCookies(): https://bugs.chromium.org/p/chromium/issues/detail?id=668932#c15

### CODE REVIEW

**Comment by aslushnikov** [comment]
Browser is a better place for this API: this should be `browser.cookies()`

**Comment by MicheleLevorato** [comment]
Good point. I'll move and rename it cause it returns all the cookies in the jar. Thanks for the feedback.

**Comment by aslushnikov** [comment]
@MicheleLevorato unfortunately, the Network domain is [not available](https://cs.chromium.org/chromium/src/content/browser/devtools/browser_devtools_agent_host.cc?sq=package:chromium&l=55) on the browser target today, so this would require some chromium work. @JoelEinbinder was planning to do something about it.

**Comment by MicheleLevorato** [comment]
Ouch. Ok, i'll stick locally with my custom code to retrieve third party cookies, looking forward for a stable solution. Thank you, @aslushnikov!

**Comment by aslushnikov** [comment]
@MicheleLevorato thanks for the PR!

**Comment by aslushnikov** [comment]
@MicheleLevorato FYI: filed #645 to track progress on this.

**Comment by dht** [comment]
Will this come with a compatible setCookies?

**Comment by aslushnikov** [comment]
@dht there's a `browser.addCookie` in the suggestion.

**Pull request closed without merging**
