### PR TITLE
Add param `threshold`  to `isIntersectingViewport`

### PR DESCRIPTION
**Pull request by ron0115**
When I write an e2e test about controlling scrollbar, I found I got visibleRatio = 0.001xxxx，I must add a threshold to finish  this judge in my situation. Looking forward to your comments

### CODE REVIEW

**Comment by ron0115** [comment]
@googlebot I signed it!

**Comment by mathiasbynens** [comment]
Since this is an API change, could you please add a test?

**Comment by jackfranklin** [comment]
I quite like this change. I wonder about the API being `{ threshold: X }` (so it's self-documenting & easy to add more options in future).

@mathiasbynens wdyt about this?

**Comment by mathiasbynens** [comment]
Agreed on using an options bag.

**Comment by ron0115** [comment]
@mathiasbynens I add a unit test about isIntersectingViewport~Thanks

**Comment by ron0115** [comment]
I couldn't handle this pr,colud anyone  please resolve the merging conflicts? @jackfranklin

**Comment by jschfflr** [comment]
@googlebot I consent.

**Comment by jschfflr** [comment]
@ron0115 I went ahead and resolved the merge conflicts while also updating the implementation a bit. Let me know if you're ok with the changes and I'm happy to get this landed :)

**Review by jschfflr — APPROVED** [review]

**Pull request merged**
