### PR TITLE
feat(docs): Minor tweak

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Issue resolution badge is a great way to signify how active the respective repository is.

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @aslushnikov

**Comment by jamesgeorge007** [comment]
cc @aslushnikov

**Review by aslushnikov — COMMENTED** [review]
what did change here?

**Comment by jamesgeorge007** [comment]
Check out the [updated file](https://github.com/GoogleChrome/puppeteer/blob/2f2ef7339be7863fabdd1e6f0d051d5b36a3d939/README.md)

**Review by aslushnikov — APPROVED** [review]

**Pull request merged**
