### PR TITLE
feat: add Page.Events.DOMContentLoaded

### LINKED ISSUE #1580: Add page.on('domcontentloaded', callback)
The page object has the ability to .wait() for the [DOMContentLoaded event](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options). It also emits the ['load' event](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-load).

It'd be nice to have a way to listen for the DOMContentLoaded event on the main frame, whether through `page.on('domcontentloaded', ...)` or through `page.mainFrame().on('domcontentloaded', ...)`.

There are cases where I want to evaluate the DOM as soon as it's ready on every navigation, and injecting JavaScript to handle it or having to call certain methods after every `goto(url, {waitUntil: 'domcontentloaded'})` is cumbersome. Emitting the DOMContentLoaded would keep things consistent between the `goto()` wait options and what is currently offered by the page's event emitter.

### PR DESCRIPTION
**Pull request by webnard**
Fixes #1580

### CODE REVIEW

**Comment by webnard** [comment]
The CLA should have been signed through my employer with the VidAngel Google Group. Was there was something incorrect in the way the CLA was signed or my association with the company?

**Comment by aslushnikov** [comment]
@webnard I don't see "VidAngel Google Group" among corporations that signed Google CLA. Are you sure this is the case?

**Review by aslushnikov — APPROVED** [review]

**Comment by aslushnikov** [comment]
The code is perfectly good, thank you for working on this. I'd love to have this in, as soon as CLA issues are resolved.

**Comment by webnard** [comment]
@aslushnikov I entered the corporation name as "VidAngel" and the _Authorized Contributors Group_ should be vidangel@googlegroups.com, of which I (ihunter@vidangel.com) should be a part. I've added this to my public Github profile as a verified email if it's needed on your end.

Let me know if I've messed something up.

**Comment by aslushnikov** [comment]
@webnard I've reached out to our CLA gurus; we'll see what they say.

**Comment by aslushnikov** [comment]
Hey @webnard,

As I was told, "VidAngel CLA is still awaiting a signature from VidAngel's representative, Ian Hunter". Can you please double-check you signed everything needed?

**Comment by webnard** [comment]
D'oh! Missed the email. It's been signed now.

**Comment by aslushnikov** [comment]
@webnard nice! It's not approved yet; I'll check status later today.

**Comment by webnard** [comment]
@aslushnikov thanks! Let me know if there's anything else you need from me

**Comment by aslushnikov** [comment]
@webnard CLA is good, thank you!

**Pull request merged**
