### PR TITLE
fix: remove broken executable "resolver" for arm64 arch

### PR DESCRIPTION
**Pull request by domoritz**
Same as https://github.com/puppeteer/puppeteer/pull/6914 but with a different commit message.

With this change, we don't need to patch puppeteer on M1. See https://github.com/puppeteer/puppeteer/issues/6622.

### CODE REVIEW

**Comment by domoritz** [comment]
I don't think the test failure is related to this change.

**Comment by domoritz** [comment]
@jackfranklin can you take a look at this?

**Comment by domoritz** [comment]
@theDavidBarton could you take a look?

**Review by theDavidBarton — APPROVED** [review]
> @theDavidBarton could you take a look?

I have taken a look gladly but I have no write access on the project, so I let @jackfranklin or other members approve it in a second round.

_Note:_ the very same change was already approved by Mathias back in February 2021, see https://github.com/puppeteer/puppeteer/pull/6914#pullrequestreview-595050869. This time commit-msg is OK.

**Comment by domoritz** [comment]
Thank you @theDavidBarton. I randomly picked you since I didn't know a better way to get the attention of someone who has write access.

I apologize if there is a process for getting reviews that I missed.

**Comment by theDavidBarton** [comment]
> Thank you @theDavidBarton. I randomly picked you since I didn't know a better way to get the attention of someone who has write access.
> 
> I apologize if there is a process for getting reviews that I missed.

No worries 😊   
I am sure soon it will be merged. Because of the M1 involvement, it is a very useful fix.

**Comment by jschfflr** [comment]
@domoritz It has been a while since this change has been uploaded. Could you verify that it's still needed?
If yes, I'm happy to get this landed :)

**Comment by domoritz** [comment]
I don't think it is with https://github.com/puppeteer/puppeteer/pull/7099.

**Comment by jschfflr** [comment]
Thanks @domoritz!

**Pull request closed without merging**
