### PR TITLE
Fix typings for ElementHandle.screenshot() options

### LINKED ISSUE #7601: [Bug]: ElementHandle.screenshot has incorrect typings
### Bug description

In [the documentation for `ElementHandle.screenshot`](https://pptr.dev/#?product=Puppeteer&version=v10.4.0&show=api-elementhandlescreenshotoptions), it's stated it takes the "same options as `page.screenshot`." However, the typings for `ElementHandle.screenshot` have `options` marked as the empty object, preventing any editor assistance or typechecking:

https://github.com/puppeteer/puppeteer/blob/f2e19276acb80e596ff5c781c9ae2bc2f2a8f363/src/common/JSHandle.ts#L816

An illustrative example:

```ts
import puppeteer from "puppeteer";

void (async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(`https://google.com`);
  const div = await page.$("div");
  await div!.screenshot({
    whatever: "property",
    typechecked: "no",
    path: 50000
  });
  await browser.close();
})();
```

This passes typechecking just fine, and (in an editor like VS Code) prompting for autocomplete within the `screenshot` options parameter (eg. with `Ctrl+Space`) produces no hints.

### Puppeteer version

10.4.0

### Node.js version

16.9.1

### npm version

7.21.1

### What operating system are you seeing the problem on?

Linux

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by lostfictions**
**What kind of change does this PR introduce?**

Typings fix.

**If relevant, did you update the documentation?**

This correction brings the typings for `ElementHandle.screenshot()` in line with [the existing documentation](https://pptr.dev/#?product=Puppeteer&version=v10.4.0&show=api-elementhandlescreenshotoptions).

**Summary**

This PR corrects the TypeScript typings for `ElementHandle.screenshot()`.

Fixes #7601.

**Does this PR introduce a breaking change?**

This isn't a breaking change, though if consumers were passing in excess or incorrect properties to the method they'll now receive a typechecking error.

### CODE REVIEW

**Comment by lostfictions** [comment]
@googlebot I signed it!

**Review by jschfflr — APPROVED** [review]
Good catch, thanks!

**Comment by lostfictions** [comment]
I unfortunately don't understand the CI failure (I looked at the docs but I'm not familiar with DocLint or what exactly it's taking issue with), so not sure I can resolve that.

**Comment by jschfflr** [comment]
@googlebot I consent.

**Pull request merged**
