### PR TITLE
feat(puppeteer): impl DOMWorld.$ for `xpath:` selector

### PR DESCRIPTION
**Pull request by mokeyish**
#5746 

**explicit locator strategy**

图片

### CODE REVIEW

**Comment by mokeyish** [comment]
@googlebot I signed it!

**Review by mathiasbynens — CHANGES_REQUESTED** [review]
This would need documentation as well. 

Either way, we're currently investigating adding this functionality more generically, so that folks can register custom query handlers and then opt-in to them for any part of the API that accepts a selector. It seems like opting in to XPath (as opposed to using [`page.$x`](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagexexpression)) would be a good fit.

**Comment by mathiasbynens** [comment]
cc @paullewis

**Comment by mathiasbynens** [comment]
We decided to go with custom query handlers instead. The implementation is currently experimental, and you can read about it here: https://github.com/puppeteer/puppeteer/releases/tag/v3.0.3 It should enable you to build what you had in mind! Please give it a try and let us know if you run into any issues.

**Pull request closed without merging**
