### PR TITLE
docs: correct spelling in README.md

### PR DESCRIPTION
**Pull request by krisztipely**
Corrected line 93 and line 113

**What kind of change does this PR introduce?**

fix

**Did you add tests for your changes?**

No

**If relevant, did you update the documentation?**

updated README.md

**Summary**

fix typo and grammar

**Does this PR introduce a breaking change?**
No

**Other information**
-

### CODE REVIEW

**Review by OrKoN — CHANGES_REQUESTED** [review]
Could you please run `npm run docs` and push re-generated docs?

**Comment by krisztipely** [comment]
I have done the `npm run docs` and pushed ✔️

**Comment by OrKoN** [comment]
Somehow your update generated an extra change reordering CSSCoverage. Could you please revert that?

**Comment by OrKoN** [comment]
Will merge the change here https://github.com/puppeteer/puppeteer/pull/11241

**Pull request closed without merging**
