### PR TITLE
Added a new external link to resources in examples

### PR DESCRIPTION
**Pull request by jancurn**

### CODE REVIEW

**Comment by jancurn** [comment]
I signed it!

**Comment by aslushnikov** [comment]
@jancurn Looking into the article, why doesn't `page.authenticate` work for the usecase?

**Comment by jancurn** [comment]
@aslushnikov I tried it and it doesn't work. I added a section about it at the end of the blog post. Other people reported similar results - please see https://github.com/GoogleChrome/puppeteer/issues/426 and https://github.com/GoogleChrome/puppeteer/issues/676

**Comment by jancurn** [comment]
@aslushnikov Oops, I realized `page.authenticate()` was used incorrectly in my testing code. I tried it again and it works. I updated the blog post to reflect this. Still there might be a few situations where page.authenticate() might not be adequate - please see the updated blog post.

**Comment by aslushnikov** [comment]
@jancurn thank you for the update.

There's also a new pull request https://github.com/GoogleChrome/puppeteer/pull/1732 that adds a proxy-specific auth. It looks like it addresses the rest of the mentioned usecases, isn't it?

**Comment by jancurn** [comment]
@aslushnikov Yeah cool. Once this feature is merged, I'll update my blog post accordingly.

**Comment by aslushnikov** [comment]
Closing in favor of #1732.

**Pull request closed without merging**
