### PR TITLE
test: ignore favicon requests in RequestServedFromCache test

### PR DESCRIPTION
**Pull request by juliandescottes**
Updates a network.spec.ts test to ignore favicon requests.

### CODE REVIEW

**Comment by OrKoN** [comment]
Note that will be using Firefox stable very soon so we will need to wait for fixes for longer.

**Comment by juliandescottes** [comment]
> Note that will be using Firefox stable very soon so we will need to wait for fixes for longer.

Oh good point, we shouldn't merge the test expectation changes. Would you still be OK with taking the fix for the test for now or do you prefer to wait until everything is in stable ?

**Comment by Lightning00Blade** [comment]
I think the change to the test is valid, and we can merge that part.

**Comment by juliandescottes** [comment]
Ok, I'll split the PR then, thanks!

**Review by Lightning00Blade — APPROVED** [review]

**Pull request merged**
