### PR TITLE
chore: continue on error for Firefox tests

### PR DESCRIPTION
**Pull request by OrKoN**
Temporarily continue on test failures in Firefox until https://github.com/puppeteer/puppeteer/issues/8361 is fixed

### CODE REVIEW

**Comment by OrKoN** [comment]
cc @juliandescottes @whimboo

**Review by whimboo — APPROVED** [review]
Not ideal but fine with me to get you unblocked. Hopefully we can get this fixed pretty soon.

**Comment by whimboo** [comment]
@OrKoN can we get this change reverted as well now that the causing commit got backed out?

**Comment by OrKoN** [comment]
I will revert this one once the other revert lands

**Pull request merged**
