### PR TITLE
ci(security): pin docker image hash

### PR DESCRIPTION
**Pull request by thiagowfx**
As per https://github.com/puppeteer/puppeteer/security/code-scanning/426

### CODE REVIEW

**Comment by Lightning00Blade** [comment]
Do you know if there is a way to auto-update this (maybe via dependabot), as we would like to keep it up-to date?

**Comment by thiagowfx** [comment]
It's not currently enabled in our config though: https://github.com/puppeteer/puppeteer/blob/main/.github/dependabot.yml

**Comment by Lightning00Blade** [comment]
Let's enable it in this PR then we can merge.

**Comment by thiagowfx** [comment]
It's orthogonal though. Even if we did not add the hash, the same pre-existing issue applies.

**Comment by thiagowfx** [comment]
...done anyway.

**Comment by Lightning00Blade** [comment]
>  Even if we did not add the hash, the same pre-existing issue applies.
Not exactly with the pin we are forcing the users to an exact version while previously we were forcing the user to install the latest version for that pin. Having the auto-update will insure we provide close to the original expectations from the users.

**Review by Lightning00Blade — APPROVED** [review]

**Pull request merged**
