### PR TITLE
feat: support chrome-headless-shell

### PR DESCRIPTION
**Pull request by mathiasbynens**
Issue: #10736

### CODE REVIEW

**Comment by OrKoN** [comment]
I think it needs a `npm run format`

**Review by OrKoN — APPROVED** [review]

**Comment by mathiasbynens** [comment]
`npm run format` done!

**Comment by OrKoN** [comment]
also, `npm run docs` is needed since the API docs are changed

**Comment by mathiasbynens** [comment]
Docs pushed!

**Comment by OrKoN** [comment]
@mathiasbynens I have overlooked missing tests, let's add a test for the chrome-headless-shell browser-data and perhaps one test making sure it's actually installable?

**Comment by OrKoN** [comment]
also, it looks like the Firefox version has gone outdated so we need to bump it in the test files.

**Review by OrKoN — APPROVED** [review]

**Pull request merged**
