### PR TITLE
test: enable test and update comments

### PR DESCRIPTION
**Pull request by Lightning00Blade**
Closes https://github.com/puppeteer/puppeteer/pull/12502

### CODE REVIEW

**Comment by whimboo** [comment]
@Lightning00Blade not sure why this PR was opened given that I'm working on a patch over on https://github.com/puppeteer/puppeteer/pull/12502.

**Comment by OrKoN** [comment]
Why does this PR close another PR? it does not look like it incorporates all other PR's changes as well.

**Comment by whimboo** [comment]
> Why does this PR close another PR? it does not look like it incorporates all other PR's changes as well.

Right, it doesn't include all but there is a bit of overlap.

**Comment by Lightning00Blade** [comment]
My bad, at the time I opened it looked the other was covered, closing will review the other PR.

**Pull request closed without merging**
