### PR TITLE
fix: cache dynamic imports

### LINKED ISSUE #8650: [Bug]: Dramatic performance drop with ESM since v14.0.0
### Bug description

Steps to reproduce the problem:

1. Set package type as module, install puppeteer v13.7.0 dependency
2. import puppeteer from 'puppeteer';
3. Run some script and measure performance
4. Update puppeteer to v14.0.0 and repeat step 3

For convenience, I created a https://github.com/feesler/puppeteer-perf package to test this issue.
```
git clone https://github.com/feesler/puppeteer-perf.git
cd puppeteer-perf
npm install
npm test
npm install puppeteer@14.0.0
npm test
```
Script will automatically download Chromium revision 982053 to discard possible difference in browser performance.

Temporary solution to fix performance for ESM packages:
```diff
- import puppeteer from 'puppeteer';
+ import puppeteer from 'puppeteer/lib/cjs/puppeteer/puppeteer.js';
```

### Puppeteer version

14.0.0 - 15.3.1

### Node.js version

16.15.1 - 18.2.0

### npm version

8.1.4

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
Node: v16.15.1
Puppeteer: 13.7.0
Browser: HeadlessChrome/101.0.4950.0
Duration: 77.40569996833801

Node: v16.15.1
Puppeteer: 14.0.0
Browser: HeadlessChrome/101.0.4950.0
Duration: 730.2374999523163

Node: v16.15.1
Puppeteer: 15.3.1
Browser: HeadlessChrome/101.0.4950.0
Duration: 742.4602999687195

Node: v18.2.0
Puppeteer: 13.7.0
Browser: HeadlessChrome/101.0.4950.0
Duration: 72.06540012359619

Node: v18.2.0
Puppeteer: 14.0.0
Browser: HeadlessChrome/101.0.4950.0
Duration: 711.3672997951508

Node: v18.2.0
Puppeteer: 15.3.1
Browser: HeadlessChrome/101.0.4950.0
Duration: 770.1029999256134
```

### PR DESCRIPTION
**Pull request by OrKoN**
Closes #8650

### CODE REVIEW

**Review by jrandolf-google — APPROVED** [review]
Node should do this themselves....*facepalm*

**Comment by Kikobeats** [comment]
I really will appreciate some explanation how what's happening here; I'm trying to understand how the perf degradation was caused and how this PR resolve the thing, but is very unclear to me; I don't understand why these helpers are even necessary 😅

**Comment by prarabdhb** [comment]
@Kikobeats From what I understood, in the previous implementation, `fs` or `debug` was imported every time the import statement was encountered. To ensure this doesn't happen, this PR stores `fs` in a variable `fs` so that it is not imported every time, improving the performance as importing can be an expensive task.

**Comment by Kikobeats** [comment]
I still feel very lost since modules (ESM/CJS) are singleton by nature, so it doesn't matter how much times you import them, it will be cached in the first call

**Comment by jrandolf-google** [comment]
> I still feel very lost since modules (ESM/CJS) are singleton by nature, so it doesn't matter how much times you import them, it will be cached in the first call

This is a reasonable assumption, but sadly this is probably not the case based on the stats.

**Pull request merged**
