### PR TITLE
Fix/element screenshot

### PR DESCRIPTION
**Pull request by cdaringe**
# problem statement

- element screenshot capture doesn't work when elements are outside of the original viewport

# solution

- use absolute coordinates

# discussion

- ~https://chromedevtools.github.io/devtools-protocol/tot/Page/#type-Viewport is ambiguous about whether `x` and `y` are relative/absolute to what reference~
- https://github.com/ChromeDevTools/devtools-protocol/issues/67

closes #1304 & #1315

### CODE REVIEW

**Comment by cdaringe** [comment]
I signed it!

**Comment by JoelEinbinder** [comment]
This looks good, but I am debating whether or not this is a bug in the protocol, and that `Page.captureScreenshot` should speak the same language as `getBoundingClientRect`

**Comment by cdaringe** [comment]
mmm, interesting.  fair. 

- `Page.captureScreenshot` in the protocol expects a `Viewport` object.  this seems correct.  it locates and defines a rectangle relative to the document.
- `getBoundingClientRect` is paired to the corresponding browser method, and returns a [DOMRect](https://developer.mozilla.org/en-US/docs/Web/API/DOMRect), which also seems correct for its use case.  it's x & y are relative to the current viewport.

the only thing i'm seeing as a viable change is expanding the `Viewport` protocol to be relative or absolute positioning aware.  however, i dont think they could use the exact same format w/out breaking backwards compatibility--one is relative, one is absolute.  thoughts?

**Review by aslushnikov — APPROVED** [review]
> This looks good, but I am debating whether or not this is a bug in the protocol, and that Page.captureScreenshot should speak the same language as getBoundingClientRect


We might want to change it in protocol, but it is not critical for now.

Thanks for the PR!

**Pull request merged**
