### PR TITLE
Enable dialog tests on all platforms

### PR DESCRIPTION
**Pull request by pavelfeldman**

### CODE REVIEW

**Comment by JoelEinbinder** [comment]
You can also enable `on-confirm.js`, the phantom test. It currently is set to expected_fail.

**Comment by aslushnikov** [comment]
For the record: this depends on https://chromium-review.googlesource.com/c/592608/

**Comment by JoelEinbinder** [comment]
#13

**Comment by aslushnikov** [comment]
@pavelfeldman Chromium could be rolled to '491334` to make this work.

**Comment by aslushnikov** [comment]
Closing as this is done in #193

**Pull request closed without merging**
