### PR TITLE
Support promises for page.waitForResponse predicate

### LINKED ISSUE #4323: Can waitForResponse take a promise instead of function or url?
**Tell us about your environment:**

* Puppeteer version: 1.14
* Platform / OS version:  Windows
* Node.js version: 10

**What steps will reproduce the problem?**
try to pass a promise to `await page.waitForResponse(response => condition)`  instead of `urlOrPredicate`.

**What is the expected result?**
expect async function to work

**What happens instead?**
no waiting as promise gets eval to truthy. 

response object has text method which is a promise to use that i need callback to be promise as well.. but if i make callback to be promise it breaks the waitForResponse function

### PR DESCRIPTION
**Pull request by josalmi**
Fixes #4323.

### CODE REVIEW

**Review by mathiasbynens — CHANGES_REQUESTED** [review]
This looks good, but it needs to be documented as well. Could you please update the API docs accordingly?

**Comment by Evanht** [comment]
Would be great to get this merged

**Comment by jackfranklin** [comment]
Hey @josalmi thanks for this PR. There's some conflicts now but I still think this is a useful feature to get in to the codebase.

Do you have any interest in picking up this PR again? No problem if not, as I can take on the work, based off this PR, but I'd be happy to help you get this landed. Thanks!

**Comment by mathiasbynens** [comment]
Merged as #6624. Thanks!

**Pull request closed without merging**
