### PR TITLE
Warning Fixed :  tsdoc-param-tag-missing-hyphan

### PR DESCRIPTION
**Pull request by tasneemkoushar**
In src/common/Page.ts
After running "npm run generate-docs",  we get warning "@param block should be followed by a parameter name and then a hyphan" in line 1052, 1055, 1058.

I corrected the syntax of the @param TSDoc comment.

### CODE REVIEW

**Comment by tasneemkoushar** [comment]
@googlebot I signed it!

**Comment by jackfranklin** [comment]
@tasneemkoushar thank you for your efforts here but it looks like another PR that's merged has fixed it. If you'd like to contribute any more fixes that'd be great - let me know if I can help :)

**Comment by tasneemkoushar** [comment]
Okay no issue, Sure I will try to fix other warnings.

**Comment by tasneemkoushar** [comment]
I pushed PR regarding some issue, the PR passed is not able to pass
run-checks for Linux, can you please help me to figure out what to do to
solve this?
I really want to contribute to puppeteer and be a part of it.

**Comment by tasneemkoushar** [comment]
My PR is https://github.com/puppeteer/puppeteer/pull/7067

**Pull request closed without merging**
