### PR TITLE
feat(launcher): add new launcher option `waitForInitialPage`

### PR DESCRIPTION
**Pull request by starrify**
The existing behavior is expected to be unchanged as the value defaults to `true`.
Adding such option would allow user to skip the initial wait.

Relevant to #3630

### CODE REVIEW

**Comment by starrify** [comment]
Hi @jschfflr @OrKoN :) Sorry for bothering you. I picked your names by randomly checking a few recently merged PRs and looking for the reviewer's name.

I understand that your team may have been rather busy working on other high priority tasks. However given that I'm rather new to contributing to this project, I'm yet unsure whether there's any other necessary step for me to do before expecting a review.

Could you kindly suggest whether there is something else that I should have done, or shall I just keep waiting patiently? Thanks! :)

**Review by jschfflr — APPROVED** [review]

**Comment by jschfflr** [comment]
Hi @starrify, your change looks good to me! Thanks for contributing to puppeteer. 
@OrKoN Do you think we need a test for this?

**Comment by OrKoN** [comment]
Could we add a test for launching with this parameter and --no-startup-window to https://github.com/puppeteer/puppeteer/blob/main/test/launcher.spec.ts?

**Comment by starrify** [comment]
Thanks a lot @jschfflr @OrKoN for your time and opinions! :)
I have added a new commit 75e5377 to this PR to introduce a new test case for this option.

**Review by OrKoN — APPROVED** [review]

**Comment by starrify** [comment]
Sorry, I forgot to run the linter for the added test case, and it turns out that the long test subject line eventually triggers linter errors.

I have pushed a new commit 11b6d12b to resolve that.

**Comment by OrKoN** [comment]
The failure seems to be unrelated to this change. I think it's being looked at separately atm.

**Comment by OrKoN** [comment]
starrify@ could you please rebase?

**Comment by starrify** [comment]
Sorry I wasn't aware of the conflict.. I've just updated the branch to have the conflicts resolved.
Please let me know if you'd like to have the commit history further cleaned, in which case I may squash the changes and do a force push to leave only one commit in the PR.

**Comment by OrKoN** [comment]
@starrify thanks! It looks fine. I have enabled auto-merge (and we squash all PRs by default) and hopefully it gets merged once CI is done (we had some flaky Firefox tests recently so it might fail again).

**Pull request merged**
