### PR TITLE
examples: add screenshot dom element example

### PR DESCRIPTION
**Pull request by ebidel**
Example for how to take a screenshot of an element on the page. We also didn't have any screenshot examples that showed how to use `clip`.

### CODE REVIEW

**Comment by aslushnikov** [comment]
Let's wait for #445 to land - it will shrink this example to a few lines

**Comment by ebidel** [comment]
SG. I'll update when that lands.

**Comment by aslushnikov** [comment]
The #445 ended up introducing the `elementHandle.screenshot` method - i think there's no need for a dedicated example any more. A code snippet in documentation would be enough.

**Comment by ebidel** [comment]
This one also showed how to use `clip` (no example for) and add padding to the screenshot. I was going to update it with the new API so we could have more runnable examples on https://try-puppeteer.appspot.com/.

**Pull request closed without merging**
