### PR TITLE
feat(request): add request.initiator() method.

### PR DESCRIPTION
**Pull request by atersolis**
add request.initiator() method, with tests and api doc

Requested by #1395

I was looking for this feature, and after reading the code, I realised it was really easy to implement.
All it took was 8 lines (+doc and tests). I wonder why it was not added earlier ?

### CODE REVIEW

**Comment by atersolis** [comment]
Oh my bad, I read the issue too fast, I didn't see #1817
Well, there were no tests, so I guess it's not completely useless
It's been more than a year since #1817 though, so what's going on ?

**Review by jschfflr — APPROVED** [review]
This change looks good to me!

**Comment by jschfflr** [comment]
@atersolis Could you make sure to sign the CLA and let the @googlebot know? Happy to land your change then :)

**Comment by jschfflr** [comment]
As there hasn't been an update on this change for a while, closing this in favor of https://github.com/puppeteer/puppeteer/pull/7614

**Pull request closed without merging**
