### PR TITLE
chore: removing unused Firefox pref `browser.safebrowsing.passwords.enabled`

### PR DESCRIPTION
**Pull request by galich**
**What kind of change does this PR introduce?**

Removing unused browser.safebrowsing.passwords.enabled pref.

**Did you add tests for your changes?**

No

**If relevant, did you update the documentation?**

No

**Summary**

Related to https://phabricator.services.mozilla.com/D192464#inline-1067780

**Does this PR introduce a breaking change?**

No

**Other information**

### CODE REVIEW

**Comment by whimboo** [comment]
Note that we should wait with merging this PR until the feature has been removed from Firefox Nightly.

**Comment by Lightning00Blade** [comment]
Hello @galich, could you please sign CLA while we wait for the new Firefox version?

Note to self: we may need to remove GitHub Action cache before testing this.

**Comment by whimboo** [comment]
Thanks Alex!

**Comment by galich** [comment]
Thanks Alex, sorry I'm still sorting out CLA

**Pull request closed without merging**
