### PR TITLE
Fix typos in docs

### PR DESCRIPTION
**Pull request by mattwelke**
**What kind of change does this PR introduce?**

Docs typo fix.

**Did you add tests for your changes?**

n/a

**If relevant, did you update the documentation?**

Yes

**Summary**

Fix typo visible on main page of site.

**Does this PR introduce a breaking change?**

No

**Other information**

n/a

### CODE REVIEW

**Comment by Lightning00Blade** [comment]
Hey @mattwelke, thank you for your PR, before we could merge it, let's revert the change to `website/versioned_docs/version-19.6.2/index.md` as it's auto-generated and we should keep it as is. 
Just a reminder to rebase and run `npm run docs` and it should be good to go. Thank you!

**Comment by mattwelke** [comment]
@Lightning00Blade I figured, but wanted to wait for confirmation. :P Fixed.

**Comment by mattwelke** [comment]
@Lightning00Blade Fixed. Note that running `npm run docs` had no effect here. It didn't generate any new files or change any of the previously-committed files.

**Comment by mattwelke** [comment]
Ran into some Git problems so I started from a fresh branch in my fork. That appears to have automatically closed this PR.

**Pull request closed without merging**
