### PR TITLE
firefox: disable experimental cookie feature sameSite=Lax by default.

### PR DESCRIPTION
**Pull request by whimboo**
@mathiasbynens can you please review? Thanks.

For details see https://bugzilla.mozilla.org/show_bug.cgi?id=1606604.

### CODE REVIEW

**Review by mathiasbynens — APPROVED** [review]

**Comment by mathiasbynens** [comment]
@whimboo Please `npm run commitlint`

**Comment by whimboo** [comment]
@mathiasbynens I have problems with installing this package. Is it just about the commit message? Which format do I have to use? Sorry for the trouble.

**Comment by mathiasbynens** [comment]
> @mathiasbynens I have problems with installing this package.

`npm install` in your local Puppeteer checkout should take care of it. Could you give that a try before re-running `npm run commitlint`?

> Is it just about the commit message? Which format do I have to use? Sorry for the trouble.

https://travis-ci.com/github/puppeteer/puppeteer/jobs/463890426#L272-L280

I could fix this myself before merging like I did for the last few patches but I'd prefer helping you to get this running locally.

**Comment by whimboo** [comment]
The failure I get when running that command locally is:

```
➜ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: typescript@3.9.2
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"3.9.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev typescript@"3.9.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by mathiasbynens** [comment]
@whimboo Have you tried the good ol' `rm -rf node_modules && npm install`?

**Comment by whimboo** [comment]
Yes, that doesn't change anything for me.

**Comment by whimboo** [comment]
@mathiasbynens any further help you can provide? Thanks

**Comment by mathiasbynens** [comment]
@whimboo I have no idea what's going on. It works locally and on CI, so there must be something different about your setup. Which versions of Node.js/npm are you using?

**Comment by whimboo** [comment]
```
➜ npm --version
7.0.3
➜ node --version
v15.0.1
```

I run `npm install npm@latest -g`,which actually downgraded to 6.14.11, but that still doesn't work. At least the failure is different:

```
> puppeteer@5.5.0-post install /Users/henrik/code/puppeteer
> node install.js

node:internal/modules/cjs/loader:900
  const err = new Error(message);
              ^

Error: Cannot find module './lib/cjs/puppeteer/node/install'
Require stack:
- /Users/henrik/code/puppeteer/install.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at download (/Users/henrik/code/puppeteer/install.js:35:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/henrik/code/puppeteer/install.js' ]
```

**Comment by jackfranklin** [comment]
@whimboo can you try running `node typescript-if-required.js` ?

**Comment by whimboo** [comment]
I run that command, and given that `lib` already existed it returned immediately as expected. As such I removed the whole folder, and run `npm install` again. That actually fixed the problem! Thanks a lot.

So should `lib` be removed automatically before running `node install`? Was that maybe some incompatibility with an older Puppeteer checkout?

**Comment by whimboo** [comment]
@jackfranklin mind a reply to my above comment? Maybe there is a bug in that script?

**Pull request merged**
