### PR TITLE
Automated spellcheck via GitHub actions (and addressing all surfaced issues)

### PR DESCRIPTION
**Pull request by SeanKilleen**
**What kind of change does this PR introduce?**

* Automated spellcheck via GitHub actions
* A cSpell configuration
* Fixes / "fixes" for any surfaced issues
* Any follow-up that might be beneficial

**Did you add tests for your changes?** No -- these should be docs changes only and visible via the GH Actions runner.

**If relevant, did you update the documentation?** Yes. :) 

**Summary**

I've been theming some contributions lately. I've now provided this to NUnit, Marten, HotChocolate, MermaidJS, Uno Platform, Prisma, and others. This repo has a lot of docs and a number of stars and I thought it also might benefit.

**Does this PR introduce a breaking change?** No.

**Other information**

### CODE REVIEW

**Comment by SeanKilleen** [comment]
Addressed most of the issues. Need to stop here for a min. Next up:

* Un-ignore some added terms and ignore them a better way via cSPell directives in the docs
* Self-review to add info

**Comment by SeanKilleen** [comment]
Alright, assuming the builds pass, I think this is ready for review.

**Review by OrKoN — CHANGES_REQUESTED** [review]
Thanks for the PR! Our documentation is generated from source code though so I think it does not make sense to add spell check for the output. Instead it'd be great to have a spell check to be part of the eslint checks. I don't think we are going to add a new GitHub action for that.

**Comment by SeanKilleen** [comment]
@OrKoN thanks for this! I'd looked around but missed the source code docs generation. I'll close this PR. 👍

ESLint does have a cspell plugin but I haven't yet used it. Perhaps someone could build on this PR with that in the future.

**Pull request closed without merging**
