### PR TITLE
docs: update README.md

### PR DESCRIPTION
**Pull request by shraddha761**
Improved sentence structure for clarity.

**What kind of change does this PR introduce?**

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by shraddha761** [comment]
@Lightning00Blade please review if you like the changes

**Comment by OrKoN** [comment]
@shraddha761 could you please sign CLA?

**Comment by Killer2OP** [comment]
> @shraddha761 could you please sign CLA?

DONE.

**Comment by Lightning00Blade** [comment]
Could you please rebase and run `npm run docs`.

**Comment by jrandolf** [comment]
Closing as stale. Please reopen in a new PR.

**Pull request closed without merging**
