### PR TITLE
block-images: fix bbc.com link

### PR DESCRIPTION
**Pull request by ebidel**
https://bbc.com doesn't appear to work.

### CODE REVIEW

**Comment by JoelEinbinder** [comment]
Is this a bug? It works for me in chrome, although it forwards me to the http site.

**Comment by ebidel** [comment]
It's dreadfully slow for me. Caused timeout issues running the sample a couple of times last night. 

What about https://news.google.com instead?

**Comment by JoelEinbinder** [comment]
Sure

**Comment by ebidel** [comment]
PTAL

**Review by JoelEinbinder — APPROVED** [review]

**Pull request merged**
