### PR TITLE
Add a6 page size

### PR DESCRIPTION
**Pull request by barryvdh**
Adds the a6 format, perhaps not as useful for website pdf's, but useful for ticket/barcode generation etc.

### CODE REVIEW

**Comment by aslushnikov** [comment]
Hey @barryvdh, thanks for the PR! Could you please update `docs/api.md` to include `a6` page format?

**Comment by barryvdh** [comment]
Yes, done :)

**Review by aslushnikov — APPROVED** [review]
Awesome, thanks

**Comment by barryvdh** [comment]
Not sure if all format (eg. up to a10?) should be included though.

**Pull request merged**
