### PR TITLE
Feature: add page.elementText

### LINKED ISSUE #2168: Feature request: add page.getInnerText(selector) or elementHandle.getInnerText()
I'm finding myself writing a lot of the following:

`page.$eval(selector, el => el.innerText)`

(when I want to read text from different elements)

I think it will be really helpful to have an abstraction like:

`page.getInnerText(selector)`

Or 

`elementHandle.getInnerText()`

### PR DESCRIPTION
**Pull request by yanivefraim**
Fixes #2168

### CODE REVIEW

**Comment by ebidel** [comment]
Hey @yanivefraim thanks for the PR. From the [contributing guide](https://github.com/GoogleChrome/puppeteer/blob/master/CONTRIBUTING.md#api-guidelines), I think this falls under:

> avoid adding "sugar" API (API that is trivially implementable in user-space) unless they're very demanded

It's easy for users to create a one liner helper:

```js
async function getText(page, selector) {
  return page.$eval(selector, el => el.innerText);
}
```

**Comment by yanivefraim** [comment]
I understand (wasn't aware of that)

**Comment by neil-s** [comment]
Is there a way to track how demanded this sugar is? Getting the text of an element feels like a common enough function that requiring users to implement their own helper or write in-context eval functions feels inappropriate.

**Comment by aslushnikov** [comment]
@neil-s it's either how much we see it requested on the issues tracker, or how many likes a related issue gets.

**Pull request closed without merging**
