### PR TITLE
Clarify error message when node is not clickable

### PR DESCRIPTION
**Pull request by pauladams8**
I've clarified the error message when the browser returns no quads for an element. The previous error message was confusing because the element in question was both an HTMLElement and visible, but not clickable because there was an overlay on the screen with a greater z-index.﻿

### CODE REVIEW

**Comment by pauladams8** [comment]
@googlebot I signed it!

**Review by jschfflr — APPROVED** [review]
This change looks good to me!

**Comment by jschfflr** [comment]
Thanks for your contribution @pauladams8!

**Comment by jschfflr** [comment]
@googlebot I consent.

**Pull request merged**
