### PR TITLE
Add note about yarn dlx

### PR DESCRIPTION
**Pull request by mifi**
See https://github.com/puppeteer/puppeteer/issues/5611#issuecomment-2509792650

**What kind of change does this PR introduce?**

documentation

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

sometimes `npx @puppeteer/browsers install` will hang indefinitely. add a suggestion to use `yarn dlx` instead

**Does this PR introduce a breaking change?**

no

**Other information**

### CODE REVIEW

**Review by OrKoN — CHANGES_REQUESTED** [review]
npx should be equivalent to yarn dlx and we should not require users to switch to yarn to work around some issues. Could you please file a bug report with the reproducible example? are you using the same version with both package runners? is it hanging inside  the respective runner or is it actually a hang during the download?

**Comment by mifi** [comment]
I cannot reproduce the problem with a simple test case, I can only reproduce it by re-running this old Github Action:

https://github.com/mifi/reactive-video/actions/runs/12104497564/job/33771544221

it hangs every time i re-run that job. But I tried copying the stuff from tests.yml into a new branch but it cannot reproduce the problem there. I don't know what's going on but it seems the conditions to trigger this bug are hard to reproduce. I'm not going to spend any more time on this, so I guess we can close this if you don't want to have dlx as a backup in the docs.

**Comment by OrKoN** [comment]
so I started a fresh job and I cannot reproduce it https://github.com/puppeteer/puppeteer/actions/runs/12114590215/job/33771385733?pr=13350

Which version does the old job using? the was a bug for older Chrome versions and older @puppeteer/browsers versions related to redirect handling. The server now redirects some old URLs to new URLs and older @puppeteer/browsers versions could not handle a redirect. Perhaps, this is what you are seeing in the old job. Let me try with that specific version.

**Comment by OrKoN** [comment]
It does not seem to reproduce on macos-13 with Chrome 117.0.5938.149 https://github.com/puppeteer/puppeteer/actions/runs/12115127014/job/33772886185?pr=13350 So the only possible explanation is that the job somehow uses an old version of @puppeteer/browsers or that there is some new bug 🤔

**Comment by mifi** [comment]
Doesn't `npx @puppeteer/browsers` use the newest stable version of `@puppeteer/browsers`? I ran it 30 minutes ago so I would think it used the newest version.

**Comment by OrKoN** [comment]
> Doesn't `npx @puppeteer/browsers` use the newest stable version of `@puppeteer/browsers`? I ran it 30 minutes ago so I would think it used the newest version.

It will use the newest version, unless there is a version installed in the repository. In that case, it will use the version installed in the current project. `npx --yes @puppeteer/browsers@latest` would ensure the latest version is always installed.

**Comment by mifi** [comment]
Oh, right! that explains it then. It was using `@puppeteer/browsers` from node_modules, which happened to be `@puppeteer/browsers@npm:1.7.1`! thanks for the pointers.
It also explains why I cannot reproduce it anymore because `@puppeteer/browsers` is now 2.4.1. Maybe the docs should be changed to recommend using the `--yes` flag?

**Comment by OrKoN** [comment]
> I see the --yes flag is just for confirming the prompt. maybe instead change all the commands in the docs to be npx @puppeteer/browsers@latest to avoid having old bugs pop up like this?

we could mention that but this is generally a feature of npx and it is documented there (it should be very similar to yarn dlx).  Many projects also prefer to run the project version to avoid sudden breakage if a new version is released that contains incompatible changes.

**Comment by mifi** [comment]
> Many projects also prefer to run the project version to avoid sudden breakage if a new version is released that contains incompatible changes.

I see. But in the case of `@puppeteer/browsers` I'd argue the opposite is true: I got this error because `@puppeteer/browsers` was too old and I hadn't run the action in a long time. If I had used `@latest` it would work. So running an old version is likely to break because maybe URLs change and servers get taken down. Also evident by the number of people who are possibly having the same issue here: #5611

**Comment by OrKoN** [comment]
Will be addressed by https://github.com/puppeteer/puppeteer/pull/13351

**Pull request closed without merging**
