### PR TITLE
Add support for authentification

### PR DESCRIPTION
**Pull request by zqsd**
This adds support for "filling the authentification popup" in puppeteer.

While it's more complex than a simple `page.authentificate('user', 'password');` this is way more flexible because it allows to use different user/password for a different websites or proxies.
Exemple for proxy auth :

```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        args: ['--proxy-server=proxy.server.tld:3128'],
        headless: true,
    });
    const page = await browser.newPage();

    await page.setRequestInterceptionEnabled(true);
    page.on('request', (request) => {
        if(request.authChallenge) { // you can also check request.authChallenge.source === 'Proxy' for instance
            request.continue({
                authChallengeResponse: {
                    response: 'ProvideCredentials',
                    username: 'yourproxyusername',
                    password: 'yourproxypassword',
                }
            });
        }
        else {
            request.continue();
        }
    });

    await page.goto('https://ip.haxx.es', {waitUntil: 'networkidle'});
    console.log(await page.evaluate(() => {
        return document.body.innerText;
    }));
})();
```

It was tricky because when receiving an authentification, the same request is done again, but since the request was already done once some data was deleted (_requestIdToRequest, _interceptionIdToRequest). I managed a hack that works to keep this data, but I suppose there is a cleaner way so I would recommend that someone with a better knowledge on this base code that me to review and make something more clean.

### CODE REVIEW

**Comment by zqsd** [comment]
signed the CLA

**Comment by aslushnikov** [comment]
Hey @zqsd,

Thank you for the PR!

Could you explain why would you want to auth on a request-per-request basis? Of course, this is 
a more flexible API, but at the same time it's more clunky.

What are the scenarios that cannot be covered with `page.authenticate`?

**Comment by zqsd** [comment]
I don't have this use case but It could be possible in some cases to have a proxy server requiring a user/password and the website requiring another user/password couple.
But yes a .authenticate method would be easier for most cases.

**Comment by aslushnikov** [comment]
@zqsd would you like to implement the `page.authenticate` instead?

**Pull request closed without merging**
