### PR TITLE
feat: allow overwrite the path for the downloads folder

### PR DESCRIPTION
**Pull request by fengmk2**
e.g.:

```bash
PUPPETEER_DOWNLOAD_PATH=/store/chromiums npm install
```

### CODE REVIEW

**Comment by fengmk2** [comment]
@googlebot I signed it!

**Comment by lcabral37** [comment]
I'm guessing this PR is dead in the water?
 Anyhow an advice, it would be nice to share the PUPPETEER_DOWNLOAD_PATH to the launcher as well  as to not having to keep track of it via the PUPPETEER_DOWNLOAD_PATH.
something like (you should take in consideration that you might not want to expose this to puppeteer-core):
```
@@ -743,11 +743,15 @@ function resolveExecutablePath(
   }
   const browserFetcher = new BrowserFetcher(launcher._projectRoot, {
     product: launcher.product,
+    path: process.env.PUPPETEER_DOWNLOAD_PATH ||
+      process.env.npm_config_puppeteer_download_path ||
+      process.env.npm_package_config_puppeteer_download_path,
   });
   if (!launcher._isPuppeteerCore && launcher.product === 'chrome') {
```
Independently of this PR turns out, great work

**Review by jschfflr — CHANGES_REQUESTED** [review]
@fengmk2 Thanks for your contribution! Could you verify it's still relevant and update it to resolve the merge conflicts? Happy to get this landed :)

**Comment by jschfflr** [comment]
This functionality has already landed in https://github.com/puppeteer/puppeteer/pull/6014. But thanks for your contribution anyways!

**Comment by fengmk2** [comment]
@jschfflr :)

**Pull request closed without merging**
