### PR TITLE
feat: port to strict typescript; convert to esm

### LINKED ISSUE #5168: Improve typescript accuracy
The intended way to use puppeteer + typescript today is by installing [`@types/puppeteer`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/puppeteer/index.d.ts). However, there are some gaps in these types:

* (big) `CDPSession` is ignorant of the protocol commands / events and return types. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f57df89f30bacee1d46dfbf40a08132b4b059ef/types/puppeteer/index.d.ts#L2151
* (nit) `Page.emulate(emulateOptions)` - types claim that both `viewport` and `userAgent` are optional, but actually both are required https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f57df89f30bacee1d46dfbf40a08132b4b059ef/types/puppeteer/index.d.ts#L519
* I use very little of the API surface, there are likely more.

These discrepancies can be avoided if the type definitions are generated from the source directly.

# Approach 1: Generate declaration files from JS

This seemed like the ideal approach - generate a `.d.ts` for every module and publish on npm. Users could use the types like this:

```js
const Browser = require('puppeteer/lib/Browser');

interface MyInterface {
  browser: Browser;
}
```

Ultimately, this didn't work, I think due to bugs within TS. Here's what would need to be done.

## Upgrade to TS 3.7

3.7 added support of `--declaration` with `--allowJs`. https://github.com/microsoft/TypeScript/issues/7546#issuecomment-535699638

## tsc errors for `events`

This pattern trips up TS when generated the declaration file:

```js
const EventEmitter = require('events');

class Blah extends EventEmitter {...}
```

The error manifests like this:

image

Using `const EventEmitter = require('events').EventEmitter` fixes this. Yeah, that works - it was [originally the only way](https://stackoverflow.com/questions/52524715/in-node-js-why-was-eventemitter-included-in-events-as-a-circular-reference) to import `EventEmitter`, and has stuck around. TS doesn't error b/c `@types/node` references a non-exported name for the default export, but for this named export it doesn't.

But, all modules that import a puppeteer class that extends `EventEmitter` still get the same error:

```
Declaration emit for this file requires using private name 'Page' from module '"/Users/cjamcl/src/puppeteer/lib/Page"'. An explicit type annotation may unblock declaration emit.
```

So, this is a blocker.

## Bad generated declaration files

`USKeyboardLayout.js` generates this `.d.ts` file:
```js
declare const _exports: {
    [x: string]: KeyDefinition;
};
export = _exports;
export type KeyDefinition = {
    keyCode?: number;
    shiftKeyCode?: number;
    key?: string;
    shiftKey?: string;
    code?: string;
    text?: string;
    shiftText?: string;
    location?: number;
};
```

Which isn't even valid:

image

Another blocker.

## :(

At this point, I gave up.

# Approach 2: Convert to TypeScript

This would certainly make great types available for puppeteer, but would be a lot of work.

# Approach 3: Just fixup `@types/puppeteer`

At the very least, I'd like to fix the lack of good CDP types in `@types/puppeteer`. Puppeteer internally defines these in `lib/externals.d.ts`. But it uses a `protocol.d.ts` that is generated based on the packaged Chromium version, so it makes sense to just import that file into `@types/puppeteer`:

```js
import Protocol from 'puppeteer/lib/protocol';

...

export interface CDPSession extends EventEmitter {
  /**
   * Detaches session from target. Once detached, session won't emit any events and can't be used
   * to send messages.
   */
  detach(): Promise<void>;

  on<T extends keyof Protocol.Events>(event: T, listener: (arg: Protocol.Events[T]) => void): this;
  
  /**
   * @param method Protocol method name
   * @param parameters Protocol parameters
   */
  send<T extends keyof Protocol.CommandParameters>(method: T, parameters?: Protocol.CommandParameters[T]): Promise<Protocol.CommandReturnValues[T]>;
}
```

This requires publishing `protocol.d.ts` to npm, and tweaking the script that generates that file to `export default Protocol;` so it can be imported.

With these changes, the following would be well-typed:

```js
const flattenedDocument = await session.send('DOM.getFlattenedDocument', { depth: -1 }); // errors if command name + param type do not match up

session.on('CSS.styleSheetAdded', styleSheetData => { ... }); // event data is properly typed
```
___

Some docs on how to use TypeScript would be good. Basically:

1. install `@types/puppeteer`
1. Using js and jsdoc ...
```js
/** @typedef {import('puppeteer').Browser} Browser */
/** @typedef {import('puppeteer').CDPSession} CDPSession */
/** @typedef {import('puppeteer').Page} Page */

/**
 * @typedef MyType
 * @property {Browser} browser
 * @property {CDPSession} session
 * @property {Page} page
 */

```

### PR DESCRIPTION
**Pull request by AviVahl**
closes #5168

This PR ports puppeteer's `lib` to strict TypeScript with ESM syntax. I've created/used a custom script to inline the jsdocs types and then continued manually fixing.

Notes:
- `.d.ts` files are automatically generated. :)
- all tests pass without any changes (no `*.spec.js` file has been changed).
- updated type tests to include all tests of `@types/puppeteer`. They pass. Not sure how to handle `ExpectType` comments (even though correct types are inferred in all cases it is used).
- compatible with user typescript projects not using `esModuleInterop` as well. tested in `"test-types"` script.
- esm migration required some `index.ts` tweaking. It now works/behaves the same as master's commonjs version (from a user's perspective), both in typed and non-typed modes.
- While some fields are prefixed with an underscore (signalling they are private), they were accessed in other classes. These are now marked as `/* @internal */` and `public`, and the `"stripInternal"` field of `tsconfig.json` has been turned on, so they don't get emitted into `.d.ts`
- protocol types are now consumed from official [devtools-protocol](https://github.com/ChromeDevTools/devtools-protocol) npm package.
- ported `fetch-devices` script to typescript (inside the `/scripts` folder).

Pain points:
- when cloning the repo itself and running `npm i` / `yarn`, the `"install"` script executes and downloads local chromium. This poses an issue when the source code is typescript-based, as the script depends on the not-yet-built `BrowserFetcher` class. I've adjusted `install.js` to check if `'./lib'` exists. If it doesn't, it will require ``ts-node/register`` and use '`./src'` directly.
- The generated `.d.ts` files require typescript@3.6+.

### CODE REVIEW

**Comment by AviVahl** [comment]
juggler tests appear to be flaky (reproduced locally with master)

**Comment by SimonSchick** [comment]
Not a maintainer but looking at the diff gives me vertigo due to the enourmous amount of changes.
Also was there any effort to stay somewhat compatible with current typings, this has been an issue before when the team tried to ship their typings vs. DTs.

**Comment by AviVahl** [comment]
@SimonSchick yeah, I realize it's big, but most new lines are due to `protocol.ts` being inlined. GitHub's diff is probably not the best tool to review the changes...

There's a lot of work being done (still WIP) to get DefinitelyTyped's tests into `./test/types/*` and ensure they pass. I use `@types/puppeteer` myself in many projects and want/need this compatibility. I'm also trying to get as many jsdocs in as I can. Super useful for auto-completions.

There were several cases where the DT types had `Promise<Buffer>`, while the actual code returns `Promise<Buffer | null>`. This was caught by the `.d.ts` being auto-generated, which is a good thing.

**Comment by SimonSchick** [comment]
I fully expected a TS port to uncover some incorrect types and those are totally cool :)

**Comment by AviVahl** [comment]
last commit made PR diff stats saner :)
also cleared the protocol types concerns by consuming them from official source.

**Comment by tomrav** [comment]
Is anyone planning on looking at this PR? I feel like it would make future contributions much easier.

**Comment by AviVahl** [comment]
Closing due to lack of response.

**Pull request closed without merging**
