### PR TITLE
fix: make more files work in strict-mode TypeScript

### PR DESCRIPTION
**Pull request by OrKoN**
Issues: #6769

### CODE REVIEW

**Review by mathiasbynens — APPROVED** [review]

**Comment by karlhorky** [comment]
Interesting, just merged this in the minor `13.1.3` update, and it broke our (previously working) CI with the error:

```
Error: puppeteerRootDirectory is not found.
    at initializePuppeteerNode
    at ../../node_modules/puppeteer/lib/cjs/puppeteer/node.js
    at __require2
    at ../../node_modules/puppeteer/cjs-entry.js
    at __require2
```

This is how we are launching Puppeteer:

```
await puppeteer.launch({
  executablePath: '/usr/bin/google-chrome-stable',  // Path to the Chrome binary on Linux
})
```

Should it break this way @OrKoN @mathiasbynens ?

**Comment by OrKoN** [comment]
@karlhorky nope, that's not expected. We try to update Puppeteer to use strict-mode TypeScript and it looks like the types are lying to us here. Let me revert that part.

**Comment by OrKoN** [comment]
actually, I think the types might be correct. I am not able to reproduce locally though but I suspect it is an issue similar to https://github.com/puppeteer/puppeteer/issues/7932? @karlhorky, could you share a reproduction?

**Comment by karlhorky** [comment]
My colleague @Josehower is working on this now, and will share a reproduction.

The basic idea behind the repro is: running a bundled Puppeteer (`esbuild`) using the code above on GitHub Actions (no `npm install` - just using the Chrome that is already installed on `ubuntu-latest`)

**Comment by Josehower** [comment]
HI, @OrKoN I am a colleague of @karlhorky thanks for the quick response and the attention to this issue. puppeteer is quite a nice tool that we use every day on our coding Bootcamp.

I have created this [basic repo](https://github.com/Josehower/puppeteer-error-demo) with a script that contains puppeteer and a GitHub workflow setup on issue comment.

you can find the error documented here. 
https://github.com/Josehower/puppeteer-error-demo/runs/5070266538?check_suite_focus=true

```
file:///home/runner/work/puppeteer-error-demo/puppeteer-error-demo/upleveled-drone.mjs:26365
        throw new Error("puppeteerRootDirectory is not found.");
              ^

Error: puppeteerRootDirectory is not found.
    at initializePuppeteerNode (file:///home/runner/work/puppeteer-error-demo/puppeteer-error-demo/upleveled-drone.mjs:26365:15)
    at ../projects/node_modules/puppeteer/lib/cjs/puppeteer/node.js (file:///home/runner/work/puppeteer-error-demo/puppeteer-error-demo/upleveled-drone.mjs:26388:72)
    at __require2 (file:///home/runner/work/puppeteer-error-demo/puppeteer-error-demo/upleveled-drone.mjs:46:50)
    at ../projects/node_modules/puppeteer/cjs-entry.js (file:///home/runner/work/puppeteer-error-demo/puppeteer-error-demo/upleveled-drone.mjs:263[9](https://github.com/Josehower/puppeteer-error-demo/runs/5070266538?check_suite_focus=true#step:4:9)5:27)
    at __require2 (file:///home/runner/work/puppeteer-error-demo/puppeteer-error-demo/upleveled-drone.mjs:46:50)
    at file:///home/runner/work/puppeteer-error-demo/puppeteer-error-demo/upleveled-drone.mjs:26401:32
    at ModuleJob.run (node:internal/modules/esm/module_job:[18](https://github.com/Josehower/puppeteer-error-demo/runs/5070266538?check_suite_focus=true#step:4:18)5:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
Error: Process completed with exit code 1.
```

if you want to test a bit the reproduction steps are:

1. create a comment on the [issue](https://github.com/Josehower/puppeteer-error-demo/issues/1)
2. Check the log of the GitHub action triggered by the comment on the [actions tab of the repo](https://github.com/Josehower/puppeteer-error-demo/actions)

you can even check the code for the [script containing puppeteer v13.1.3 ](https://github.dev/Josehower/puppeteer-error-demo/blob/main/upleveled-drone.mjs)

As you can see on the image the error is being ended from line 26364.

image


As additional information, I tried patching puppeteer with the possible solution presented on the PR [7933](https://github.com/puppeteer/puppeteer/pull/7933) whit no success.

we use a puppeteer bundled with esbuild and the base file with the script is a ts file.

again thanks for your time and looking forward to your answer.

Good Energy 👍👍👍👍

**Comment by OrKoN** [comment]
@Josehower Thanks for the details. Could you try out the following CL https://github.com/puppeteer/puppeteer/pull/7967 ?

**Comment by Josehower** [comment]
@OrKoN Thanks ill try it and let you know

**Comment by Josehower** [comment]
@OrKoN I can confirm fix #7967 works fine, again thanks for the fast response. 

looking forward to this PR being merged.

**Pull request merged**
