### PR TITLE
Disable flaky test on firefox

### LINKED ISSUE #7175: The test "Page.click - should double click the button" is repeatedly failing for Firefox on main
One example invocation: https://github.com/puppeteer/puppeteer/runs/2448603012?check_suite_focus=true
@whimboo Could you take a look at this?

### PR DESCRIPTION
**Pull request by jschfflr**
This reverts commit 49a54cfc93947a313427f6aa39512c644c9ae001.

### CODE REVIEW

**Comment by jschfflr** [comment]
Let's disable the test for firefox for now to get the actions running again.

**Review by OrKoN — APPROVED** [review]

**Comment by mathiasbynens** [comment]
Hmm, did this pass the `npm run commitlint` check? The commit message does not seem to follow the format we require (which allows to auto-generate the changelog + release notes + figure out the next release version number).

**Comment by jschfflr** [comment]
Hmm, interesting. It might have been a problem with the auto merge. I enabled it last week and made sure that the commit message matches the lint but I renamed the cl afterwards which probably changed it again. 
Not sure how to proceed in this case - what do you recommend?

**Comment by mathiasbynens** [comment]
Fixed via force-push

**Comment by jschfflr** [comment]
Thanks!

**Pull request merged**
