### PR TITLE
refactor: simplify EmulationManager

### PR DESCRIPTION
**Pull request by aslushnikov**
EmualationManager used to be injecting touch hooks to properly
support touch emulation.

However, these are no longer necessary, since https://crbug.com/133915
is long fixed.

### CODE REVIEW

**Review by JoelEinbinder — COMMENTED** [review]
Can we add a test for emulating a touchscreen (not mobile) without refreshing and make sure it still appears that touch is enabled on the page. I’m skeptical.

**Comment by aslushnikov** [comment]
> Can we add a test for emulating a touchscreen (not mobile) without refreshing and make sure it still appears that touch is enabled on the page. I’m skeptical.

Nice catch!

**Review by JoelEinbinder — APPROVED** [review]
Need to eslint ignore the modernizr.js file. And can you update the description? This is a functionality change now.

**Comment by aslushnikov** [comment]
Nah, no functional change - you didn't let me to do one.

**Pull request merged**
