### PR TITLE
fix: also kill Firefox when temporary profile is used

### PR DESCRIPTION
**Pull request by whimboo**
This particular check had been added because of issues with killing the Firefox process on Windows. But that was fixed in Firefox 96 and we should be able to remove the workaround.

Lets see if CI is happy with it.

### CODE REVIEW

**Comment by whimboo** [comment]
There are quite some failures visible on Windows so we most likely have to delay landing of this PR.

**Comment by whimboo** [comment]
@OrKoN as we discussed we would still like to get this workaround removed given that the underlying issue in Firefox is really fixed. Failures in the launcher spec tests are most likely caused by some combination of running these in sequence. As such I would propose (for now) to just separate out the `should filter out ignored default arguments` for Firefox given that we do not have that many arguments as Chrome and we would remove arguments optionally added. Please let me know if that would work for you. Thanks.

**Review by OrKoN — APPROVED** [review]

**Comment by OrKoN** [comment]
LGTM thanks!

**Comment by whimboo** [comment]
@OrKoN I just noticed that we have issues locally with our expected results JSON file which is keyed by test name. With having the same test name twice now (once for Chrome and one more for Firefox) we cannot explicitly mark the expected data due to duplicated keys. I would suggest that we slightly rename the Firefox test so that the name is different if that's ok.

**Pull request merged**
