### PR TITLE
fix: Chrome for Testing downloads have a new URL

### LINKED ISSUE #11925: [Bug]: Reliable Browser Download Broken
### Steps to reproduce

It seems the download path has changed? cc @mathiasbynens 

https://developer.chrome.com/blog/chrome-for-testing/

```
#Download the latest available Chrome for Testing binary corresponding to the Stable channel.
npx @puppeteer/browsers install chrome@stable
```

### Expected results

Browser downloads as expected.

### Actual results
```
Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/linux64/chrome-linux64.zip
    at /home/bewo/cf-repos/challenge-platform/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:102:31
    at ClientRequest.requestCallback (/home/bewo/cf-repos/challenge-platform/node_modules/@puppeteer/browsers/lib/cjs/httpUtil.js:79:13)
```

### PR DESCRIPTION
**Pull request by OrKoN**
See https://github.com/GoogleChromeLabs/chrome-for-testing/pull/108

Closes #11925

To make the older releases of @puppeteer/browsers to work with the new endpoint: use the `--base-url https://storage.googleapis.com/chrome-for-testing-public` parameter on the command line or the `baseUrl` on the InstallOptions https://pptr.dev/browsers-api/browsers.installoptions.

### CODE REVIEW

**Review by mathiasbynens — APPROVED** [review]
LGTM once the tests pass (which would mean the old assets have been copied over to the new bucket)

**Comment by worenga** [comment]
related https://github.com/puppeteer/puppeteer/issues/11925

**Comment by christian-bromann** [comment]
@OrKoN is it possible to release this soonish? This is currently breaking all WebdriverIO tests for people that don't have a specific browser version defined. Also could you please backport this change to `@puppeteer/browser@v1.x` since we can't update `@puppeteer/browser` due to the fact that it dropped support for Node.js v16. WebdriverIO v8 can't drop Node.js v16 support.

**Comment by ngan** [comment]
You can work around this for now, like so:

```
npx @puppeteer/browsers install chrome@stable --path /usr/local --base-url https://storage.googleapis.com/chrome-for-testing-public
```

**Comment by OrKoN** [comment]
@christian-bromann tests do not pass yet, meaning the binaries are not back-filled at the new endpoint.

@mathiasbynens have you resumed dashboard updated before the sync was done?

**Comment by OrKoN** [comment]
@mathiasbynens looks like it is been partially back-filled.

**Comment by renemadsen** [comment]
@OrKoN Will there be a new npm package soon, so we can fix all our broken ci/cd which uses WebdriverIO and in turn puppeteer?

**Comment by mathiasbynens** [comment]
> @mathiasbynens have you resumed dashboard updates before the sync was done?

The sync was completed last night, after which I resumed dashboard updates.

However, any existing software that uses the CfT API to get version numbers (e.g. “which version is the latest Canary?”) but hardcodes the old URL format instead of using the `-with-downloads` endpoints might now receive a version number for which the downloads are not available on the old host. This software must be updated.

Thanks for updating Puppeteer!

**Comment by christian-bromann** [comment]
> You can work around this for now, like so:

Thanks a lot, this will allow us to move forward without having to backport this change to v1.x.

**Pull request merged**
