### PR TITLE
Updated proxy-from-env to ^1.1.0

### PR DESCRIPTION
**Pull request by ArjenKorevaar**
See issue #6659

### CODE REVIEW

**Comment by ArjenKorevaar** [comment]
@googlebot I signed it!

**Comment by ArjenKorevaar** [comment]
Could someone please review this PR ? It seems trivial but is currently blocking our migration to a new npm registry config.

**Comment by ArjenKorevaar** [comment]
@mathiasbynens could you please have a look at this PR? Thanks in advance!

**Comment by ArjenKorevaar** [comment]
@jackfranklin  maybe ?

**Comment by ArjenKorevaar** [comment]
@mathiasbynens Please take a look!

**Comment by ArjenKorevaar** [comment]
@mathiasbynens  @jackfranklin  @jschfflr

**Review by jschfflr — APPROVED** [review]

**Comment by jschfflr** [comment]
The change looks good to me but the merge commit does not conform to the conventional-commits standards. 
Please remove that one as it seems to be empty anyways and I'm happy to merge.

**Comment by ArjenKorevaar** [comment]
The merge was an auto update from github, in an attempt to fix build errors. Anyway, rolled it back to the previous rebase onto main.

**Comment by jschfflr** [comment]
Ah, I see :D
Now I ran into the same button - I'm not that familiar with the github ui yet.
Maybe we can get around the problem by fixing the commit message while squash merging.

**Comment by jschfflr** [comment]
I think there might be something off with the github actions. To verify, I added new pull request with the same changes here: https://github.com/puppeteer/puppeteer/pull/6817

**Comment by jschfflr** [comment]
Just as I suspected, the pull request from me went through without a problem. 
I'll file an issue to fix the github actions.

**Pull request merged**
