### PR TITLE
Add User-Agent with Puppeteer version to WebSocket request

### PR DESCRIPTION
**Pull request by headlesstesting**
This will add the User-Agent header to WebSocket requests, with the Puppeteer version.

The reason why we wanted to create this PR is because we can then offer our customers the most compatible browser version depending on the Puppeteer version they are using to connect to our service.

Developers use this method to connect to our service:
`const browser = await puppeteer.connect({
  browserWSEndpoint: 'wss://chrome.headlesstesting.com'
})`

When we receive a request, we can check the user-agent and determine the most compatible browser version.

### CODE REVIEW

**Comment by headlesstesting** [comment]
@googlebot I signed it!

**Review by jschfflr — APPROVED** [review]
@headlesstesting This change looks good to me, thanks!

**Comment by jschfflr** [comment]
@headlesstesting Can you resolve the conflicts? Happy to get this landed!

**Comment by jschfflr** [comment]
@googlebot I consent.

**Pull request merged**
