### PR TITLE
feat(chromium): roll Chromium to r586620

### LINKED ISSUE #3106: Calling a exposed function inside an evaluateOnNewDocument function does not work on Chrome 70
* Puppeteer version: 1.7.0
* Platform / OS version: Linux x64
* Node.js version: v10.0.0

This code works on Chorme/Chromium 69, "Hello from logExposedFunction1" and "Hello from logExposedFunction2" are logged to console, with Chrome 70 only  "Hello from logExposedFunction2" is logged.

I noticed logging `logExposedFunction1` logs `ƒ () { [native code] }` and `logExposedFunction2` logs a js code from `__puppeteer_evaluation_script__:2`

Was there an API change around this? I did not see anything at the change log 

```js
const puppeteer = require('puppeteer')

const start = async () => {
  const browser = await puppeteer.launch({
    headless: false,
  });

  const page = await browser.newPage();

  await page.exposeFunction('logExposedFunction1', () => {
    console.log('Hello from logExposedFunction1')
  })
  await page.evaluateOnNewDocument(() => {
    logExposedFunction1()
  })

  await page.goto('https://example.com');

  await page.exposeFunction('logExposedFunction2', () => {
    console.log('Hello from logExposedFunction2')
  })
  await page.evaluate(() => {
    logExposedFunction2()
  })
}

start()
```

### PR DESCRIPTION
**Pull request by aslushnikov**
This roll includes:
- https://crrev.com/584293 - DevTools: execute scripts in addScriptToEvaluateOnLoad in order
- https://crrev.com/585630 - DevTools: introduce Browser.grantPermissions

References #846.
Fixes #3106.

### CODE REVIEW

**Comment by JoelEinbinder** [comment]
I thought we merged this already?

**Review by JoelEinbinder — APPROVED** [review]

**Comment by aslushnikov** [comment]
> I thought we merged this already?

Nah, I accidentally removed the branch while cleaning up my fork.
The Appveyour is unhappy though - looks like this will require some more effort.

**Comment by aslushnikov** [comment]
For the record: bisected this down to https://chromium-review.googlesource.com/c/chromium/src/+/1171482

**Comment by aslushnikov** [comment]
Fix is in CQ: https://chromium-review.googlesource.com/c/chromium/src/+/1194035

**Comment by aslushnikov** [comment]
Close in favor of https://github.com/GoogleChrome/puppeteer/pull/3153

**Pull request closed without merging**
