### PR TITLE
add typescript type definitions 🌹

### PR DESCRIPTION
**Pull request by basarat**
For a demo of the developer experience you can try out https://github.com/basarat/chromes :heart:

### CODE REVIEW

**Comment by basarat** [comment]
I signed it!

**Comment by plantain-00** [comment]
It seems that they want to generate typescript definitions from jsDoc automatically: #219

**Comment by aslushnikov** [comment]
@basarat thank you for the PR!

Like it was said, we're in the middle of adding auto generated typescript definitions: #219

**Comment by basarat** [comment]
no worries :rose:

**Pull request closed without merging**
