### PR TITLE
Update block-images.js

### PR DESCRIPTION
**Pull request by vpotseluyko**
Maybe you have changed api, or..

### CODE REVIEW

**Comment by vsemozhetbyt** [comment]
See https://github.com/GoogleChrome/puppeteer/commit/b73737302a5dbfc5cd67f37be8460e53ab4f417f

**Comment by vpotseluyko** [comment]
So, is my commit is correct. :)

**Comment by vsemozhetbyt** [comment]
@vpotseluyko I think the example reflects the tip of tree (master) state, it will work properly if a user upgrades to the v1.0.0-rc and it is also in sync with the current https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

**Comment by vpotseluyko** [comment]
Oh, understood. Extremely sorry.

**Comment by vsemozhetbyt** [comment]
@vpotseluyko Do not be discouraged, it is a common thing in this repository, docs and examples always outrun a bit the last npm version, so many people get confused)

**Pull request closed without merging**
