### PR TITLE
captureBeyondViewport as screenshot optinal param

### PR DESCRIPTION
**Pull request by galr52**
making the captureBeyondViewport as an optional parameter to the screenshot

https://github.com/puppeteer/puppeteer/issues/7043

### CODE REVIEW

**Comment by galr52** [comment]
@googlebot I signed it!

**Comment by galr52** [comment]
@googlebot I signed it!

**Comment by sadym-chromium** [comment]
Thanks for the PR! One thing: if `captureBeyondViewport: false`  is used, the screenshot beyond the viewport will be blank. The logic with `Emulation.setDeviceMetricsOverride` should be returned as well in case of `captureBeyondViewport: false`: https://github.com/puppeteer/puppeteer/pull/6805/files

**Review by sadym-chromium — CHANGES_REQUESTED** [review]
Thanks for the PR! One thing: if `captureBeyondViewport: false`  is used, the screenshot beyond the viewport will be blank. The logic with `Emulation.setDeviceMetricsOverride` should be returned as well in case of `captureBeyondViewport: false`: https://github.com/puppeteer/puppeteer/pull/6805/files

**Comment by galr52** [comment]
> Thanks for the PR! One thing: if `captureBeyondViewport: false` is used, the screenshot beyond the viewport will be blank. The logic with `Emulation.setDeviceMetricsOverride` should be returned as well in case of `captureBeyondViewport: false`: https://github.com/puppeteer/puppeteer/pull/6805/files

i fixed your comment, i hope that i understand you correctly.

**Review by sadym-chromium — APPROVED** [review]

**Pull request merged**
