### PR TITLE
test: mark Page.close test as failing in Firefox

### PR DESCRIPTION
**Pull request by mathiasbynens**
This should fix the CI build (#4930).

### CODE REVIEW

**Review by aslushnikov — APPROVED** [review]
i think this is fixed in a new version of juggler. Shall we roll it as well?

**Comment by mathiasbynens** [comment]
SGTM. I could update https://github.com/GoogleChrome/puppeteer/blob/a5f03ce1c85c2630739f2a894a303c68632aa250/experimental/puppeteer-firefox/package.json#L12 myself but I would need access to the upload bucket to make sure a corresponding download exists. @aslushnikov could you give `mathiasb@google.com` access?

**Comment by paulirish** [comment]
ayo guys. just a driveby, but did this bucket access get sorted out?

**Comment by mathiasbynens** [comment]
Not yet

**Pull request merged**
