### PR TITLE
fix(input): clicking an element should take into account frame position

### LINKED ISSUE #684: Clicking element inside iFrame does not give any response
I am clicking an element inside an iframe which should give me a different frame/view, that is move into the view represented by that element. If i click the element manually,the url does not change. So, I guess only the frame is changed. The element is being clicked properly since there are no errors for that. However nothing happens when it is clicked and returns error when I do `page.waitForNavigation()`.
Here is the debug log listening for mouse and keyboard clicks.
puppteer
Also made sure proper element is clicked referring to #618. Here is portion of code that handles clicking the element inside iframe : 
```javascript
var frames = await page.frames();
var myframe = frames.find(f => f.name() === 'mygurukuliframe_submenu'); 
const attselector = '#imgid_12';
const attel = await myframe.$(attselector);
const outerHTML = await attel.evaluate(e => e.parentNode.outerHTML);
console.log('the outerhtml: ', outerHTML);
await attel.click({button:'middle'});
await page.waitForNavigation();
await page.screenshot({path : 'example.png'});
browser.close();
```

Please mention if any further info is needed and help if it can be resolved.

### PR DESCRIPTION
**Pull request by JoelEinbinder**
fixes #684

### CODE REVIEW

**Comment by aslushnikov** [comment]
The `.getBoxModel` returns something different for me.  It probably should be fixed/enhanced first.

**Comment by JoelEinbinder** [comment]
It returns different numbers when scale is involved, which we currently don't handle in Puppeteer.

**Comment by veb** [comment]
Sorry if I'm not supposed to comment here, but I pulled this fix to try this snippet (posted by @paulirish in #618) and it *does* click if I comment out the `outerHTML` stuff.

```
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch({headless: false, slowMo: 250});
const page = await browser.newPage();
await page.goto('https://www.w3schools.com/TAgs/tryit.asp?filename=tryhtml_button_test');

const frames = await page.frames();
const tryItFrame = frames.find(f => f.name() === 'iframeResult');
const framedButton = await tryItFrame.$('button');

const outerHTML = await framedButton.evaluate(e => e.parentNode.outerHTML);
console.log('the outerhtml: ', outerHTML); // to verify we're talking about the right element.. (we are.)

framedButton.click();
})();
```

How is the evaluate stuff supposed to work in this context?

In another script, I tried to select an input to type in some data but I keep getting `framedInput.type` is not a function:

```
    const framedInput = await iframe.$('input#fm-login-id');
    framedInput.click(usernameSelector);
    framedInput.type(username);
```

Am I being an idiot?!

**Comment by JoelEinbinder** [comment]
@veb Paul's code was slightly out of date. `elementHandle.evaluate` was dropped. `elementHandle.type` is coming shortly in #801.

Edit: #943 does not add `elementHandle.evaluate`, I got confused.

**Review by aslushnikov — APPROVED** [review]

**Comment by veb** [comment]
Thanks @JoelEinbinder I've tested those changes on #801 before it was merged and they work perfectly. I'm just waiting for this one to be merged and then selecting and typing into iframes will be worked just as intended 👍

**Pull request merged**
