### PR TITLE
chore: browser fetcher returns latest revision by default

### PR DESCRIPTION
**Pull request by sadym-chromium**
The change needed for reusing Puppeteer's BrowserFetcher:
https://github.com/GoogleChromeLabs/chromium-bidi/pull/38#discussion_r682427228

### CODE REVIEW

**Comment by mathiasbynens** [comment]
The code change LGTM, but before we can land this (if it’s still needed?), we should also update the API docs and add a test.

**Comment by jschfflr** [comment]
@sadym-chromium could you add the changes that Mathias proposed or otherwise close this pull request?

**Comment by sadym-chromium** [comment]
@jschfflr postponing the PR for now

**Comment by mathiasbynens** [comment]
It sounds like we no longer need this for chromium-bidi. If we're not realistically going to pick this PR back up again, let's close it instead of marking it as a draft forever?

**Comment by jschfflr** [comment]
@sadym-chromium I'll close this pr for now but feel free to reopen if needed!

**Pull request closed without merging**
