### PR TITLE
Add method to disable JavaScript

### PR DESCRIPTION
**Pull request by JoelEinbinder**
#462

### CODE REVIEW

**Comment by aslushnikov** [comment]
This might be interesting for @pavelfeldman and @dgozman.

I'm not aware what's the state of `Emulation.setScriptExecutionDisabled` - are we fine with un-experimenting it or thinking about removing.

**Comment by JoelEinbinder** [comment]
I have no strong feelings about whether or not we should add this.

**Comment by benjamingr** [comment]
Why a negaitve? Wouldn't it make more sense to publicly expose an enabling method (like in the Android WebView API)?

**Comment by Garbee** [comment]
This would actually be a fantastic thing to have to test site interaction without JS. Like a site where you progressively enhance features only when JS is available.

**Comment by JoelEinbinder** [comment]
@benjamingr If I recall correctly, WebView has JavaScript disabled by default.

**Comment by benjamingr** [comment]
They do, the question is whether not to align with their API and call it `setJavaScriptEnabled` or something like that.

**Comment by aslushnikov** [comment]
Bikeshedding method name: I like the `page.disableJavaScript(true)` - concise and easily searchable in documentation.

**Comment by JoelEinbinder** [comment]
But then what happens when someone types `page.disableJavaScript()`  :)

**Comment by aslushnikov** [comment]
> But then what happens when someone types page.disableJavaScript() :)

@JoelEinbinder Well...
```
(node:90673) AssertionError [ERR_ASSERTION]: First argument must be of type "boolean"!
    at Console.assert (console.js:164:23)
    at Page.disableJavaScript (/Users/lushnikov/prog/puppeteer/lib/Page.js:505:12)
    at __dirname (/Users/lushnikov/prog/puppeteer/b.js:6:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by pavelfeldman** [comment]
I'd rather call it `page.setJavaScriptEnabled(boolean)`. Always disliked `disabled = true` constructs.

**Comment by benjamingr** [comment]
Another bikeshed, in Android and other platforms that use the webview the incorrect `Javascript` capitalization is used. I think we shouldn't use it and should use the compliant `JavaScript` instead.

**Review by benjamingr — APPROVED** [review]
Would love to see this land

**Comment by JoelEinbinder** [comment]
Pavel wins the shed!
image

**Review by aslushnikov — APPROVED** [review]

**Comment by loilo** [comment]
Awesome!

**Pull request merged**
