### PR TITLE
fix(launcher): ensureInitialPage awaits forever

### PR DESCRIPTION
**Pull request by rbochenski**
There might be a situation when event was sent before listener attached and initialPageCallback is never called.

### CODE REVIEW

**Comment by JoelEinbinder** [comment]
I want to fix this bug on the Chromium side rather than introducing a timeout.

**Comment by rbochenski** [comment]
> I want to fix this bug on the Chromium side rather than introducing a timeout.

I would be more than happy to see problem solved on Chromium. How long it will take?
If few weeks/months it might be good to use this PR in the meantime.

**Comment by aslushnikov** [comment]
> There might be a situation when event was sent before listener attached and initialPageCallback is never called.

@rbochenski Can you please clarify how's this possible? Is there any repro I can try locally to see this happenning?

**Comment by rbochenski** [comment]
> > There might be a situation when event was sent before listener attached and initialPageCallback is never called.
> 
> @rbochenski Can you please clarify how's this possible? Is there any repro I can try locally to see this happenning?

I will prepare something for you.

**Comment by aslushnikov** [comment]
@rbochenski I'll close this for now; feel free to send another PR once you're ready.

**Pull request closed without merging**
