### PR TITLE
fix(typescript): allow defaultViewport to be 'null'

### LINKED ISSUE #6885: [7.0.4] Type defaultViewport can't be null (to take all window space)
* Puppeteer version: 7.0.4
* Node.js version: 12.x

Usually, to make viewport taking all the available space in window we need to set `defaultViewport` to null:

```js
const puppeteer = require('puppeteer');

(async () => {
    const windowWidth = 1472;
    const windowHeight = 828;
    
    const browser = await puppeteer.launch({
        headless: false,
        args: [
            "--enable-automation",
            "--start-maximized",
            `--window-size=${windowWidth},${windowHeight}`,
            "--no-sandbox",
            "--disable-setuid-sandbox",
            "--disable-dev-shm-usage",
            "--proxy-server='direct://",
            "--proxy-bypass-list=*",
            "--disable-gpu",
            "--disable-accelerated-2d-canvas",
        ],
        defaultViewport: null,
        pipe: true,
    });

    const page = (await browser.pages())[0];
    const url = 'https://www.blizzard.com/en-us/';

    await page.goto(url, {
        waitUntil: 'load',
    });
})();
```

This doesn't seem to be allowed in typescript (`defaultViewport` must be of type `Viewport` or `undefined`):

image

But leaving it undefined does not give the desired result.

### PR DESCRIPTION
**Pull request by christian-bromann**
Fixes: #6885

This aligns with how `defaultViewport` can be applied to a [`Page`](https://github.com/puppeteer/puppeteer/blob/main/src/common/Page.ts#L391) or [`Target`](https://github.com/puppeteer/puppeteer/blob/main/src/common/Target.ts#L69).

### CODE REVIEW

**Review by Niek — APPROVED** [review]

**Comment by searleser97** [comment]
Is this going to be ready for the next release?

**Comment by christian-bromann** [comment]
ping @jackfranklin

**Review by sadym-chromium — APPROVED** [review]

**Comment by zoltan-boros** [comment]
@christian-bromann, are you going to merge this?

**Comment by christian-bromann** [comment]
@zoltan-boros I don't have any permissions to merge

**Comment by zoltan-boros** [comment]
@jackfranklin, your review and approval is missing to merge this change.
Could you review it, please?

**Pull request merged**
