### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
**What kind of change does this PR introduce?**

Fix typos.

**Did you add tests for your changes?**

Nope.

**If relevant, did you update the documentation?**

Yes.

**Summary**

Fix typos found via `codespell -S package-lock.json -L currenty,afterall`

**Does this PR introduce a breaking change?**

Nope.

**Other information**

### CODE REVIEW

**Comment by OrKoN** [comment]
Thanks for the PR! Could you please rebase an exclude changes to the website directory? It contains generated files.

**Comment by OrKoN** [comment]
Would you mind running `npm run docs` and pushing once more? I think fixes caused some reformatting in the docs/ folder which is also auto-generated from the source.

**Review by OrKoN — APPROVED** [review]

**Comment by kianmeng** [comment]
> Would you mind running `npm run docs` and pushing once more? I think fixes caused some reformatting in the docs/ folder which is also auto-generated from the source.

@OrKoN Sorry, miss this message. Thanks for follow this up.

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
