### PR TITLE
fix(performance): cache isolatedHandle

### PR DESCRIPTION
**Pull request by Lightning00Blade**

### CODE REVIEW

**Comment by OrKoN** [comment]
preformence -> performance

**Comment by OrKoN** [comment]
@Lightning00Blade pls fix the formatting/docs

**Comment by Lightning00Blade** [comment]
I have not gather data, will do and report it back here.

**Comment by Lightning00Blade** [comment]
@OrKoN 
```
Current 94ms, 87ms, 93ms, 102ms. 96ms 
Last release: 92ms, 94ms, 117ms, 94ms, 118ms 
```


```
import { launch } from "puppeteer";

(async () => {
  const browser = await launch({
    headless: true,
  });

  const page = await browser.newPage();

  await page.setContent(`
    <html>
      <head>
        <title>Hello, world!</title>
      </head>
      <body>
        <h1>Hello, <span>world</span>!</h1>
      </body>
    </html>
  `);
  const start = performance.now();
  const element = await page.$("h1");
  const element2 = await element.$("span");
  console.log(await element.isVisible());
  console.log(await element2.isVisible());

  await element.screenshot({
    path: "screenshot.png",
  });
  const end = performance.now();
  console.log("Screenshot taken in", end - start, "ms");

  await page.screenshot();
  await browser.close();
})();
```
So the more you use an `ElementHandle` the better the performence.

**Comment by OrKoN** [comment]
@Lightning00Blade could you measure it for like 100-1000 ElementHandle operations to get a number % for the improvement?

**Comment by Lightning00Blade** [comment]
What should the test do exactly, we need to trigger the decorator so we need to do X operations?

**Comment by OrKoN** [comment]
@Lightning00Blade it could be anything that something that can clearly say by how much it is improved? Or perhaps do more runs and get the average.

**Review by OrKoN — APPROVED** [review]

**Comment by Lightning00Blade** [comment]
Previous version with average of  `34.23254930973053` ms.
After change with average of `30.94756257534027` ms.


Test code 
```ts

**Pull request merged**
