### PR TITLE
chore: format docs

### PR DESCRIPTION
**Pull request by jrandolf-google**
This PR reenables formatting due to the code samples.

### CODE REVIEW

**Review by OrKoN — APPROVED** [review]

**Comment by ushuz** [comment]
Sorry to disturb, is there a way to see docs for older version? Searching on the new docs site is quite frustrating.

**Comment by OrKoN** [comment]
@ushuz Hey, thanks for the feedback? Do you have anything specific we can improve on the new site? You can see docs for the older version on GitHub, e.g., https://github.com/puppeteer/puppeteer/blob/v14.2.0/docs/api.md

**Comment by ushuz** [comment]
**Update (July 21, 2022)**: Old docs are still available at: https://puppeteer.github.io/pptr.dev/#?version=v15.2.0

---

@OrKoN Thanks for the quick response. I'm using [Chinese translation site](https://zhaoqize.github.io/puppeteer-api-zh_CN/) that offers both previous versions and old search as a workaround.

---

For example, search `reload`:

Old search ([Chinese translation site](https://zhaoqize.github.io/puppeteer-api-zh_CN/) still uses the old layout and search in case anyone else is looking for it):
image

New search:
image

---

Also, the new search may sent visitors to a weird `xxx_1` page that only shows method signature, instead of documentation, for example, clicking `waitForSelector` result ...

image

... brings me to https://pptr.dev/api/puppeteer.page.waitforselector_1 (signature only) ...

image

... instead of https://pptr.dev/api/puppeteer.page.waitforselector (the one-page doc I was looking for)

image

---

Appreciate the effort to improve docs, but have to say that the new doc site is not as easy-to-use as the old one.

**Comment by OrKoN** [comment]
@ushuz thanks for the feedback! The extra pages should be removed from the site as it was caused by multiple type signatures for the method which will be removed. We will keep improving the docs further!

**Pull request merged**
