### PR TITLE
feat(coverage): Support Node.js coverage instrumentation.

### PR DESCRIPTION
**Pull request by mikeal**
This patch detects coverage and inserts proxy objects to handle coverage on instrumented evaluate calls.

This patch works great, I used a bunch of puppeteer tests I have locally to verify, but I'm not entirely sure how to write a unit test for puppeteer itself for it. 

Additionally, the typescript linter is failing on globals detection and I have no idea how to suppress them.

### CODE REVIEW

**Comment by mikeal** [comment]
I'll explain a bit more about why this patch is necessary so that people don't have to read this entire thread https://github.com/GoogleChrome/puppeteer/issues/1054

`page.evaluate(() => {})` will .`toString()` the function and eval it in the page's context.

When coverage is enabled in Node.js it hooks into require and instruments every line of code. This means that the `.toString()` value has *partial* instrumentation and will fail with `cv_randomid` is undefined errors.

This patch detects coverage and inserts proxy objects for the instrumentation objects that communicate back to the Node.js process which lines have been called.

**Comment by mikeal** [comment]
I've got a tool, along with tests that enable coverage, https://github.com/mikeal/cappadonna , using this branch.

**Comment by bcoe** [comment]
this is awesome, let me know if there's anything I can do to help see this over the finish line. I'm excited to add documentation for this to Istanbul, perhaps we can also call this out in puppeteer's docs somewhere?

**Comment by aslushnikov** [comment]
Hey @mikeal, thanks for the effort of fixing this.

There's a bunch of missing pieces, like evaluations in child frames and page navigations, but these are all fixable. There's also a little bit of race conditions related to async nature exposed functions. I, however, have a stronger concern about this whole approach.

The logic in this PR is very much istanbul-related. Puppeteer, however, shouldn't depend on istanbul, nor should it have any code that relies on internal istanbul machinery, such as `__coverage__` global.

I see that this PR solves two problems:
1. It makes istanbul to work with puppeteer
2. It teaches istanbul to compute code coverage inside browser

The (2) should be solved separately: there's a superior approach for the browser code coverage (see #320). 

The core issue with (1) is that istanbul's code preprocessing yields side-effects: the function's toString method return different values with and without coverage.

A simple fix would be to change istanbul to override `Function.prototype.toString` with something like this:
```js
(() => {
  const originalToString = Function.prototype.toString;
  Function.prototype.toString = () => {
    const code = originalToString.call(this);
    return code.replace(/\bcov_[^;]+/g, '');
  }
})();
```

**Comment by mikeal** [comment]
A few things:

* Istanbul is really the defacto-standard for JS based coverage. There isn't much else that is in wide use.
* It's a fairly standard practice among test tools and frameworks in JS to dynamically enable coverage features based on `__coverage__`, you can find code in `tap` for instance that does just that.

This all said, I can just as easily stick this code in `cappadonna` instead of `puppeteer`. I figured I should send it as a PR so that you can stop getting strange issue reports when people enable coverage :)

> A simple fix would be to change istanbul to override Function.prototype.toString with something like this:

If that happened then we wouldn't be able to hack in support the way we just did ;)

It's great that you have a way to collect better coverage statistics in Chrome but for most practical use cases we're going to need a unified coverage report across Node.js and browser code. Tap jumps through a lot of hoops to capture child processes and whatnot without any user configuration or intervention.

In the end a Chrome-centric solution just isn't very useful if we have to manually integrate it into the rest of an ecosystem that already "just works."

**Pull request closed without merging**
