### PR TITLE
Add default flag to export tagged PDFs in anticipation of Chrome 81

### PR DESCRIPTION
**Pull request by chrisjpatty**
The most recent Chrome Canary has the ability to generate "tagged" PDF documents using the new command line flag: `--export-tagged-pdf`, and is slated for official release in Chrome 81.

Tagged PDF documents provide the meta structure needed for screen readers to correctly announce PDF documents via a screen reader and related technologies. As I can't imagine a compelling reason why a generated PDF document shouldn't contain this meta information, as it in no way alters the content or visual appearance of the PDF, I've added this command-line flag as a default argument. 

This also addresses #3298

### CODE REVIEW

**Comment by chrisjpatty** [comment]
@googlebot I signed it!

**Comment by chrisjpatty** [comment]
It's been a few months and I just wanted to ping someone to see if this can be reviewed. Any chance I can get some eyes on this small change? Thanks!
CC: @mathiasbynens

**Comment by KyleCrowley** [comment]
I'd like to bump this issue as well. 

According to the following [issue](https://bugs.chromium.org/p/skia/issues/detail?id=8148l) on the Chromium bug tracker, this option _should_ be enabled by default, but I am unsure if that is the case in Chrome 81.

Obviously we can add the `--export-tagged-pdf` argument ourselves, but I believe it makes more sense to enable it by default in puppeteer if it's not already enabled by default in Chrome.

**Comment by robschmuecker** [comment]
Hey @KyleCrowley 
Please could you point us in the direction of where this could be experimented with? We are looking to implement this and as of May haven't been able to get it to work.  Also not finding this in the docs anywhere as a supported tag - could you please perhaps point in the right direction?
Many thanks in advance,
Rob.

**Comment by KyleCrowley** [comment]
> Hey @KyleCrowley
> Please could you point us in the direction of where this could be experimented with? We are looking to implement this and as of May haven't been able to get it to work. Also not finding this in the docs anywhere as a supported tag - could you please perhaps point in the right direction?
> Many thanks in advance,
> Rob.

@robschmuecker Apologies. I know it's a bit late but I just now saw this.

There's not a whole lot of documentation surrounding this feature, and when I was first investigating if Chrome supported PDF tagging, I went down a rabbit hole of GitHub issues, Chromium issues, etc.

That being said, [this](https://chromium-review.googlesource.com/c/chromium/src/+/1970742) is the merge that added PDF tagging when the `--export-tagged-pdf` flag is enabled.

In terms of using this feature in puppeteer, you need to add the flag when you launch puppeteer like so:

```typescript
const browser: Browser = await launch({
    args: ["--export-tagged-pdf"]
});
```

Until this PR is merged, you'll need to launch puppeteer with that argument.

As mentioned in [my initial comment on this PR](https://github.com/puppeteer/puppeteer/pull/5337#issuecomment-625963379), my understanding is that newer versions of Chrome/Chromium (81+) _should_ have this option enabled by default, but I haven't verified this myself. At the very least, if the flag is not enabled by default in Chromium, it should be in puppeteer, unless there's a compelling reason I'm unaware of (performance?).

**Comment by noelleleigh** [comment]
Looks like the file this PR changes has been removed. The flag should now be added to [src/node/Launcher.ts](https://github.com/puppeteer/puppeteer/blob/main/src/node/Launcher.ts). 

I can confirm that Puppeteer 5.5.0 (Chromium 88.0.4298.0) does not create tagged PDFs by default.

**Review by jschfflr — CHANGES_REQUESTED** [review]
@chrisjpatty Thanks for your contribution! Could you verify that this change is still relevant and if yes, resolve the merge conflict? Happy to get this landed :)

**Comment by jschfflr** [comment]
Closing this as Chromium is now exporting tagged PDFs by default.

**Comment by averms** [comment]
> Closing this as Chromium is now exporting tagged PDFs by default.

Doesn't seem to be the case for me. Installed latest puppeteer from npm, ran the `hn.js` example from the README and I got a file called hn.pdf. Checked with `pdfinfo` and it doesn't seem to be tagged:

```
Creator:        Chromium
Producer:       Skia/PDF m93
CreationDate:   Mon Oct  4 02:42:51 2021 EDT
ModDate:        Mon Oct  4 02:42:51 2021 EDT
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          2
Encrypted:      no
Page size:      594.96 x 841.92 pts (A4)
Page rot:       0
File size:      92024 bytes
Optimized:      no
PDF version:    1.4
```

I changed the script to add `--export-tagged-pdf` to the launch args and `pdfinfo` reported it as tagged:

```
Creator:        Chromium
Producer:       Skia/PDF m93
CreationDate:   Mon Oct  4 02:47:14 2021 EDT
ModDate:        Mon Oct  4 02:47:14 2021 EDT
Tagged:         yes
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          2
Encrypted:      no
Page size:      594.96 x 841.92 pts (A4)
Page rot:       0
File size:      272206 bytes
Optimized:      no
PDF version:    1.4
```

**Comment by jschfflr** [comment]
Thanks for checking this! I just looked through the release notes and saw that tagged pdf export is now [shipped by default](https://blog.chromium.org/2020/07/using-chrome-to-generate-more.html).
I'll investigate to see what's going on...

**Comment by jschfflr** [comment]
While it looks like tagged PDF is enabled by default on headfull Chromium, headless still requires the flag. Could you maybe verify that headfull Chromium does indeed generate tagged PDFs by default and if yes, file a bug on https://crbug.com/ to make tagged PDFs the default in headless too? Thanks!
Happy to land this in the meantime if you update the change :)

**Comment by averms** [comment]
> While it looks like tagged PDF is enabled by default on headfull Chromium, headless still requires the flag. Could you maybe verify that headfull Chromium does indeed generate tagged PDFs by default

Even full Chromium doesn't seem to generate tagged PDFs on my end. This is on Linux but I'm going to check on my Windows machine too.

EDIT: yup it's tagged on Windows but not on Linux.

> and if yes, file a bug on https://crbug.com/ to make tagged PDFs the default in headless too? Thanks! Happy to land this in the meantime if you update the change :)

Someone already [filed one in June](https://bugs.chromium.org/p/chromium/issues/detail?id=1224704).

**Comment by jschfflr** [comment]
@googlebot I consent.

**Comment by jschfflr** [comment]
@averms Thanks for checking!
I resolved the merge conflicts here - happy to get this landed :)

**Review by jschfflr — APPROVED** [review]

**Pull request merged**
