### PR TITLE
readme: new new temp logo

### PR DESCRIPTION
**Pull request by paulirish**
aint no party like a bikeshed party.

made with feedback from @ebidel and @addyosmani

### CODE REVIEW

**Review by ebidel — APPROVED** [review]
smashed it.

**Review by JoelEinbinder — APPROVED** [review]
The Mac bias is apparent. I made a windows version:
image

**Comment by JoelEinbinder** [comment]
Can the background be transparent instead of white?
screen shot 2017-08-15 at 11 06 37 am

**Comment by paulirish** [comment]
> Can the background be transparent instead of white?

oh shoot. yeah it was supposed to be. thanks!

**Comment by paulirish** [comment]
its transparent now.

note that gh's css forces a white bg color on images there, for whatever reason:

image

**Comment by aslushnikov** [comment]
Nicee

**Pull request merged**
