### PR TITLE
test: Update expectations for firefox support of continueRequest

### PR DESCRIPTION
**Pull request by juliandescottes**
Should be merged once [Bug 1850680](https://bugzilla.mozilla.org/show_bug.cgi?id=1850680)  and [Bug 1898565](https://bugzilla.mozilla.org/show_bug.cgi?id=1898565) are available in Nightly

### CODE REVIEW

**Comment by whimboo** [comment]
This PR has to wait given that the patches from Julian got backed out before the weekend.

**Comment by OrKoN** [comment]
looks like changes has landed? Could you please run `npm run format`?

**Comment by OrKoN** [comment]
I have pushed the formatting changes

**Review by OrKoN — APPROVED** [review]

**Comment by juliandescottes** [comment]
Thanks for the re-format and merge!

**Pull request merged**
