### PR TITLE
fix(install): respect environment proxy config when downloading Firef…

### PR DESCRIPTION
**Pull request by benelliott**
…ox version metadata on install

Issues: #6573

### CODE REVIEW

**Review by mjzffr — APPROVED** [review]
Thanks!

**Comment by matt-glich** [comment]
Appreciate the help!

**Comment by gamma032steam** [comment]
Do we need a [documentation](https://github.com/puppeteer/puppeteer/blob/v10.0.0/docs/api.md#environment-variables) update?

> HTTP_PROXY, HTTPS_PROXY, NO_PROXY - defines HTTP proxy settings that are used to download and **run Chromium**.

Perhaps
"HTTP_PROXY, HTTPS_PROXY, NO_PROXY - defines HTTP proxy settings that are used to download and run a browser.".

**Comment by jschfflr** [comment]
@benelliott Could you verify that this change is still relevant and if yes, please update it? Happy to get this landed :)

**Review by jschfflr — APPROVED** [review]

**Comment by jschfflr** [comment]
@googlebot I consent.

**Comment by benelliott** [comment]
Thanks @jschfflr!

**Comment by jschfflr** [comment]
Sure! Happy to help :)

**Pull request merged**
