### PR TITLE
docs: fix typos in `docs` and `website` folder

### PR DESCRIPTION
**Pull request by thapasusheel**
**What kind of change does this PR introduce?**

This PR introduce the typo fix in files of `docs` and `website`

**Did you add tests for your changes?**

No

**Summary**

**Does this PR introduce a breaking change?**

No

**Other information**

```pseudo
platfrom > platform
```

### CODE REVIEW

**Review by OrKoN — CHANGES_REQUESTED** [review]
These files are generated and we should fix it in the source.

**Comment by thapasusheel** [comment]
> These files are generated and we should fix it in the source.

@OrKoN  How can I do so?

**Comment by OrKoN** [comment]
@thapasusheel could you update `packages/browsers/src/browser-data/types.ts` (line 31) and run `npm run docs`

**Comment by thapasusheel** [comment]
> @thapasusheel could you update `packages/browsers/src/browser-data/types.ts` (line 31) and run `npm run docs`?

I have updated that file and run `npm run docs`. Do I need to commit docs file too?

image

**Comment by OrKoN** [comment]
Yes, and also revert the changes to the website folder.

**Comment by thapasusheel** [comment]
> Yes, and also revert the changes to the website folder.

Please review it.

**Review by OrKoN — APPROVED** [review]
Thanks!

**Pull request merged**
