### PR TITLE
test: convert license text file to LF line endings

### PR DESCRIPTION
**Pull request by andreastt**
See https://github.com/GoogleChrome/puppeteer/pull/4320#issuecomment-493006944.

Should fix the checkout problems on Unix file systems.

### CODE REVIEW

**Review by aslushnikov — APPROVED** [review]

**Comment by aslushnikov** [comment]
Thanks @andreastt!

**Comment by aslushnikov** [comment]
@andreastt can you please sign google's CLA to make the bot happy?

**Comment by andreastt** [comment]
I will follow up with the legal department here at Mozilla on that and get back to you soon.

**Comment by andreastt** [comment]
@aslushnikov Should be ready now.

I’ve now been added to the Mozilla corporate CLA list, but I had to resign the commit with my @mozilla.com email.

**Pull request merged**
