### PR TITLE
chore(types): Add types to in-page functions like `evaluate`(`Handle`), `waitForFunction`, etc

### PR DESCRIPTION
**Pull request by stevenwdv**
**What kind of change does this PR introduce?**

Improving TypeScript types

**Did you add tests for your changes?**

Currently: no, but I did update the existing test code

**If relevant, did you update the documentation?**

Not yet

**Summary**

Solves `evaluate`, `evaluateHandle`, and other related functions not enforcing types.
See #8485

**Does this PR introduce a breaking change?**

Yes.

- Functions accepting page functions (e.g. `Page.evaluate`) do not accept strings anymore (except Page.evaluateOnNewDocument).
  → Rewrite calls to use regular functions where possible. For dynamic functions, use the [`Function()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function), [`AsyncFunction()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction) or [`GeneratorFunction()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction) constructor.
- Generic parameters of these functions have changed.
  → Just remove them from each call. Types will now be inferred automatically.
- Types of these functions and of `JSHandle<T>` are now properly enforced, leading to rejection of improperly typed programs.
  → Add type casts or correct code where necessary.
- Some type aliases in `EvalTypes` have been removed.
  → I don't expect many people to use these, but use the new alternatives where necessary.
- `ElementHandle` is now `ElementHandle<ParentNode>` instead of `ElementHandle<Element>` by default, because it actually always supported things like `Document` as well.
  → Cast to `ElementHandle<Element>` where needed.

**Other information**

Some breaking changes can be reversed (e.g. string overloads or old `EvalTypes` type aliases). However, keeping string overloads will make typing a lot harder and will likely lead to TypeScript rejecting correct programs (at least when I tried it).

I did go all out for this one, and you may find I changed some types that shouldn't be / didn't need to be changed, then just tell me.

I intentionally made this a draft PR for now. I'm doing this in my free time because I felt like it so I'm not sure if I'll have time to update docs and such.

### CODE REVIEW

**Comment by jrandolf-google** [comment]
Closed in favor of https://github.com/puppeteer/puppeteer/pull/8547.

**Comment by stevenwdv** [comment]
@jrandolf Hey I don't wish to be too salty, but you could have at least told me you were working on this, now it feels like I did all of this for nothing.

Anyway, I'm glad the types are there at least. Feel free to take any code from my PR where desired...

**Comment by jrandolf-google** [comment]
@stevenwdv I wouldn't cut yourself short! I've also checked out your PR and kept note of some of the ideas used there. The general layout changed drastically though through internal discussions.

**Comment by stevenwdv** [comment]
@jrandolf Ah ok I'm glad to hear that :) At first it seemed to me like you didn't look at the code.

**Pull request closed without merging**
