### PR TITLE
test: disable a flaky Firefox test on Windows

### PR DESCRIPTION
**Pull request by OrKoN**
See https://github.com/puppeteer/puppeteer/actions/runs/11556521600/job/32164435107#step:10:408

### CODE REVIEW

**Comment by OrKoN** [comment]
@whimboo this test started being flaky suddenly yesterday 

```
  10) Chromium-Specific Launcher tests
       Puppeteer.launch |browserURL| option
         should throw when trying to connect to non-existing browser:
     ProtocolError: Protocol error (session.new): session not created Maximum number of active sessions RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
SessionNotCreatedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:709:5
createSession@chrome://remote/content/webdriver-bidi/WebDriverBiDi.sys.mjs:121:13
onPacket@chrome://remote/content/webdriver-bidi/WebDriverBiDiConnection.sys.mjs:198:55
onMessage@chrome://remote/content/server/WebSocketTransport.sys.mjs:127:18
handleEvent@chrome://remote/content/server/WebSocketTransport.sys.mjs:109:14

      at Callback.<instance_members_initializer> (packages\puppeteer-core\src\common\CallbackRegistry.ts:116:12)
      at new Callback (packages\puppeteer-core\src\common\CallbackRegistry.ts:121:3)
      at CallbackRegistry.create (packages\puppeteer-core\src\common\CallbackRegistry.ts:27:22)
      at BidiConnection.send (packages\puppeteer-core\src\bidi\Connection.ts:105:28)
      at Function.from (packages\puppeteer-core\src\bidi\core\Session.ts:31:39)
      at Function.create (packages\puppeteer-core\src\bidi\Browser.ts:75:35)
      at FirefoxLauncher.createBiDiBrowser (packages\puppeteer-core\src\node\BrowserLauncher.ts:396:35)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at FirefoxLauncher.launch (packages\puppeteer-core\src\node\BrowserLauncher.ts:167:19)
      at launch (test\src\mocha-utils.ts:546:21)
      at Context.<anonymous> (test\src\chromiumonly.spec.ts:70:34)
```

do you have some ideas about what might be going on?

**Comment by whimboo** [comment]
What specifically makes this test Chromium specific? If it should work in Firefox as well, we should probably move it to a different place. 

Also do you have some trace logs? I assume that the call to `browser1.disconnect()` might not have been successful and left the active session alone?

**Comment by OrKoN** [comment]
> What specifically makes this test Chromium specific? If it should work in Firefox as well, we should probably move it to a different place.

There is a TOOD for that in the test code :)

**Comment by OrKoN** [comment]
> Also do you have some trace logs? I assume that the call to browser1.disconnect() might not have been successful and left the active session alone?

I do not have a trace but in the code we launch a fresh browser instance. Is it possible that Firefox is started without errors if another browser instance already has the port opened?

**Review by Lightning00Blade — APPROVED** [review]

**Comment by whimboo** [comment]
> I do not have a trace but in the code we launch a fresh browser instance. Is it possible that Firefox is started without errors if another browser instance already has the port opened?

Ah good point! We should probably have the same behavior as for Marionette and shutdown the browser if the Websocket port is still in use and cannot be acquired. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1927721.

**Comment by whimboo** [comment]
Just to note as well, it's not clear to me why it started failing now. We did not change anything in that code.

**Comment by OrKoN** [comment]
Looks like it is not flaky after a rewrite of the test.

**Pull request closed without merging**
