### PR TITLE
Improve type of predicate function

### PR DESCRIPTION
**Pull request by karlhorky**
Hi there, thanks for all of your hard work on Puppeteer! So amazing, the projects that can be built with it.

A quick PR to improve the types for `page.waitForRequest` and `page.waitForResponse` - types are inspired by the DefinitelyTyped `@types/puppeteer` package:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c43191a8f7a7d2a47bbff0bc3a7d95ecc64d2269/types/puppeteer/index.d.ts#L1883-L1885

### CODE REVIEW

**Review by jackfranklin — APPROVED** [review]
Nice improvement, thank you!

**Comment by karlhorky** [comment]
No problem!

Do I need to fix something so that it auto-merges? The tests seem like they flaked out...

**Comment by karlhorky** [comment]
@mathiasbynens @jackfranklin do you have any guidance for these reconnect timeouts? Still failing after I merged `main` in again...

```
  386 passing (3m)
  317 pending
  1 failing

  1) Launcher specs
       Puppeteer
         Browser.disconnect
           should reject navigation when browser closes:
     Error: expect(received).toBe(expected) // Object.is equality

Expected: "Navigation failed because browser has disconnected!"
Received: "Protocol error (Page.navigate): Target closed."
      at Context.<anonymous> (test/launcher.spec.ts:146:31)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jackfranklin** [comment]
Might be a FF nightly test issue. @mathiasbynens wdyt? We could disable the test if it continues to flake. The changes in this PR are only TS types so shouldn't cause this issue.

**Comment by karlhorky** [comment]
Similar, but slightly different error this time:

```
  386 passing (4m)
  317 pending
  1 failing

  1) Launcher specs
       Puppeteer
         Puppeteer.connect
           should be able to reconnect:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/puppeteer/puppeteer/test/launcher.spec.ts)
```

**Comment by jackfranklin** [comment]
@whimboo would you mind taking a look at this PR? It seems to always hit some FF issue around timeouts. I'm not sure if this is a problem with a recent FF nightly build, or some other issue, but it seems to happen consistently at the moment on this and other PRs.

**Comment by karlhorky** [comment]
@jackfranklin Since this PR is unrelated to the test failures, maybe this PR could be merged in the meantime?

**Comment by whimboo** [comment]
@jackfranklin yes this is a known issue with Firefox Nightly at the moment. See https://bugzilla.mozilla.org/show_bug.cgi?id=1701168. Also you disabled this test for now via https://github.com/puppeteer/puppeteer/pull/7062.

@karlhorky please rebase against main and push again. The tests should  pass now.

**Comment by karlhorky** [comment]
Nice, thanks @jackfranklin and @whimboo !

**Pull request merged**
