### PR TITLE
Use randomized folder names for user profile directories

### LINKED ISSUE #360: directory not empty error when running multiple puppeteer processes in parallel
I'm running puppeteer with the latest node.js on the latest macOS Sierra. I wrote a script that uses puppeteer to scrape a web page with a URL parameter passed into process.argv. When I attempt to running multiple processes in parallel, I get the following error:

```
/usr/local/lib/node_modules/puppeteer/node_modules/rimraf/rimraf.js:312
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/puppeteer/.dev_profile1/Local Storage/leveldb'
    at Object.fs.rmdirSync (fs.js:852:18)
    at rmkidsSync (/usr/local/lib/node_modules/puppeteer/node_modules/rimraf/rimraf.js:355:25)
    at rmdirSync (/usr/local/lib/node_modules/puppeteer/node_modules/rimraf/rimraf.js:333:7)
    at rimrafSync (/usr/local/lib/node_modules/puppeteer/node_modules/rimraf/rimraf.js:303:9)
    at /usr/local/lib/node_modules/puppeteer/node_modules/rimraf/rimraf.js:341:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (/usr/local/lib/node_modules/puppeteer/node_modules/rimraf/rimraf.js:340:26)
    at rmdirSync (/usr/local/lib/node_modules/puppeteer/node_modules/rimraf/rimraf.js:333:7)
    at rimrafSync (/usr/local/lib/node_modules/puppeteer/node_modules/rimraf/rimraf.js:303:9)
    at /usr/local/lib/node_modules/puppeteer/node_modules/rimraf/rimraf.js:341:5
```

I do not get this error message when running each process sequentially. It looks like it's trying to clean out a temp folder, but each parallel process is trying to clean the same folder at the same time.

### PR DESCRIPTION
**Pull request by aslushnikov**
This will make it much harder for puppeteer browsers to collide
on profile directories.

Fixes #360

### CODE REVIEW

**Comment by JoelEinbinder** [comment]
Is there a reason we cant just check if the folder exists, and then increment a counter by 1? Bringing in crypto seems pretty heavy.

**Comment by aslushnikov** [comment]
I don't know if `fs.mkdir` is atomic on win and decided not to rely on it. Do you have any information about this?

Regarding the crypto, the `randomBytes` method takes a few milliseconds to generate [according to the doc](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback).

**Comment by JoelEinbinder** [comment]
I'll take your word for it.

**Review by JoelEinbinder — APPROVED** [review]

**Comment by MiniCodeMonkey** [comment]
Somewhat related to this ticket - is there a way to use puppeteer but keep using the same profile directory? (I want to persist my session/cookies for subsequent requests to the same website)

**Comment by aslushnikov** [comment]
@MiniCodeMonkey the [cookies api](https://github.com/GoogleChrome/puppeteer/issues/53) will allow you to store all the cookies somewhere and restore them later. Will it satisfy your needs?

**Pull request merged**
