### PR TITLE
docs: Just removed a superfluous line break char in README.md

### PR DESCRIPTION
**Pull request by Mehver**
docs: Just removed a superfluous line break char in `README.md`.

### CODE REVIEW

**Comment by SynthesisDu** [comment]
docs: Just removed a superfluous line break char in README.md

**Comment by SynthesisDu** [comment]
@google-cla @googlebot I have signed CLA

**Comment by Mehver** [comment]
@googlebot I have signed CLA

**Comment by OrKoN** [comment]
Closed in https://github.com/puppeteer/puppeteer/pull/8211

**Pull request closed without merging**
