### PR TITLE
docs(troubleshooting): add official node image example

### PR DESCRIPTION
**Pull request by nuragic**
Also add a note explaining that alpine is not reliable for CI (add reference to https://github.com/GoogleChrome/puppeteer/issues/4823) for context.

### CODE REVIEW

**Comment by BrandonCopley** [comment]
@nuragic which version of puppeteer does this run with?

**Comment by nuragic** [comment]
The latest one right now. It should work for any further version as well, because it's puppeteer that installs the corresponding chrome version.

**Comment by jschfflr** [comment]
@nuragic Thanks for your contribution! Could you verify that this change is still relevant and up to date? If yes, I'm happy to get this landed!

**Comment by jschfflr** [comment]
Closing this as there haven't been any updates on this change for a while. Feel free to reopen if this is still relevant!

**Pull request closed without merging**
