### PR TITLE
Add attribute(key) and property(key) methods to ElementHandle

### PR DESCRIPTION
**Pull request by batiste**
Related to my issue here https://github.com/GoogleChrome/puppeteer/issues/438

I implemented those methods. Those are just simple shortcuts but I think they might be useful to write tests.

```js
    it('should return attribute', SX(async function() {
      await page.setContent('<section id="testAttribute">43543</section>');
      const element = await page.$('section');
      expect(element).toBeTruthy();
      expect(await element.attribute('id')).toBe('testAttribute');
    }));
```

### CODE REVIEW

**Comment by batiste** [comment]
I signed it!

**Comment by aslushnikov** [comment]
Nicee, thank you for the PR!

We're currently working on #382, and the feature will add the `properties()` method that would return object handles.

Given this, let's scope this PR only to the `attribute()` method.

**Comment by batiste** [comment]
@aslushnikov very well. I removed the property method.

**Comment by aslushnikov** [comment]
@batiste please run the `npm run doc` command to update table-of-contents in `api.md` and satisfy documentation linter.

**Comment by batiste** [comment]
@aslushnikov done!

**Review by aslushnikov — APPROVED** [review]

**Pull request merged**
