### PR TITLE
Add support install form mirror host that use redirect

### LINKED ISSUE #1740: Not support install form a mirror host that use 3xx http status code
### Steps to reproduce

**Tell us about your environment:**
```shell
$ npm config get puppeteer_download_host
https://npm.taobao.org/mirrors
```
* Puppeteer version: HEAD
* Platform / OS version: Windows 10 64
* Node.js version: v9.2.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. run `npm i GoogleChrome/puppeteer --save`

**What is the expected result?**

Successfully installed.

**What happens instead?**
```shell 
$ npm i puppeteer --save

> puppeteer@0.13.0 install E:\work\sms-bomber\node_modules\puppeteer
> node install.js

ERROR: Failed to download Chromium r515411! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 302. URL: https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/515411/chrome-win32.zip
    at ClientRequest.https.get.response (E:\work\sms-bomber\node_modules\puppeteer\utils\ChromiumDownloader.js:198:21)
    at Object.onceWrapper (events.js:254:19)
    at ClientRequest.emit (events.js:159:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:439:20)
    at TLSSocket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
```

### PR DESCRIPTION
**Pull request by gucong3000**
Closes #1740

### CODE REVIEW

**Comment by gucong3000** [comment]
I signed it!

**Comment by gucong3000** [comment]
AppVeyor build failed.
I think I need some help.

**Review by aslushnikov — APPROVED** [review]
Thank you

**Comment by aslushnikov** [comment]
@gucong3000 the appveyor just flaked; no big deal.

**Comment by emmanuelbeaudoin** [comment]
I signed it!

**Pull request merged**
