### PR TITLE
feat(chromium): roll Chromium to r590951

### PR DESCRIPTION
**Pull request by aslushnikov**
Just a healthy roll.

### CODE REVIEW

**Review by JoelEinbinder — CHANGES_REQUESTED** [review]
Worker behavior is different in this release. We should be a bit careful

**Comment by aslushnikov** [comment]
@JoelEinbinder in what release and what's different?

**Comment by aslushnikov** [comment]
For the record (as per discussion with @JoelEinbinder):

> @dgozman made workers not interrupt JavaScript on runtime evaluate; we might be able to remove some worker hacks.

Waiting for Joel to validate that our workers are reliable enough to roll this.

**Review by JoelEinbinder — APPROVED** [review]
Looks good

**Pull request merged**
