### PR TITLE
fix(frame): Fix Frame.waitFor's XPath pattern detection

### PR DESCRIPTION
**Pull request by xprudhomme**
Up to now, only strings starting with '`//`' are considered as to XPath selectors. 

Unfortunately, this is too restricting and leads to errors especially when asking the page to wait for XPath selectors not starting with '`//`'. 

If the XPath is something like '`(//div)[4]/@itemprop`' then it is passed to the waitForSelector method and eventually document.querySelector, which in turn throws an error because it does not recognize it as a valid CSS selector.

Because of this, I had to implement something like this in my code:

```javascript
await isXPathSelector(selector)
            ? page.waitForXPath(selector)
            : page.waitForSelector(selector);
```

This fix allows the use of valid XPath selectors starting with parenthesis and to be recognized as such by the Frame's waitFor method.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
This needs tests.

**Comment by xprudhomme** [comment]
It's my first PR here. Never done any test for this before.
Any help appreciated for implementing required tests.
Thanks :)

**Comment by mathiasbynens** [comment]
Look for the existing `waitForXPath` tests and add some examples that failed without your patch, but now work.

**Comment by xprudhomme** [comment]
Ok thanks.

I've changed the xPathPattern to allow for the use of XPath starting with not only "//" but also with an opening parenthesis.

In my last commit, I've also added a new test accordingly.

**Review by jschfflr — APPROVED** [review]
@xprudhomme Thanks for your contribution! Please resolve the merge conflicts and I'm happy to get this landed!

**Comment by jschfflr** [comment]
@googlebot I consent.

**Pull request merged**
