### PR TITLE
fix: page.pdf producing an invalid pdf

### PR DESCRIPTION
**Pull request by tjacobs3**
**What kind of change does this PR introduce?**
Bugfix

**Summary**
When defining a chunk size for `<CDPSession>.send('IO.read', { handle, size })`, the `CDPSession` will occassionally indicate that it has reached the end of file without sending a full pdf. This is documented by the associated issue.

This behavior is not reproducible when leaving out the size parameter. Since the size parameter is not required on the CDPSession side and is merely a suggestion on the stream side, we can safely leave it out.

Refs: #7757

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by OrKoN** [comment]
Thanks for the fix. I'd really appreciate if you add a failing test case that is fixed by this.

**Comment by OrKoN** [comment]
Disregard my previous comment, I think we can land it without new test cases. Could you please add a TODO like `TODO: bring the size parameter back once Chromium issue crbug.com/1290727 is resolved.`

**Review by OrKoN — APPROVED** [review]

**Comment by OrKoN** [comment]
I will add a TODO myself in a follow-up PR.

**Comment by MartinFalatic** [comment]
@OrKoN Thank you for expediting this, and for tracking down a potential root cause in Chromium itself!

@tjacobs3 Thanks for the effective workaround to keep puppeteer working properly while we await the fix in Chromium!

**Pull request merged**
