### PR TITLE
chore: update prettier globs and format files

### PR DESCRIPTION
**Pull request by nschonni**
**What kind of change does this PR introduce?**

refactoring

**Did you add tests for your changes?**

**If relevant, did you update the documentation?**

**Summary**

Updated to get a clean run with prettier running across all files. Ignore some generated and test content that shouldn't be formatted

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by Kikobeats** [comment]
Thanks for this; All PRs are broken linter was added but the code is not properly formatted.

If @johanbay @mathiasbynens approve this, we can rebase the rest of PRs 🙏

**Comment by OrKoN** [comment]
I think for js files we use prettier through eslint to avoid conflicts. Would it work without conflicts with eslint? Thanks a lot for the PR and I appreciate if you can rebase it if it's compatible with eslint.

**Comment by nschonni** [comment]
Yes, ESLint prettier passes out to the main library, and uses the same config

**Comment by nschonni** [comment]
@OrKoN gave it a rebase and added in a few ignores from a CI failure. Unfortunately the prettierignore doesn't merge with gitignore currently, so there is a bit of duplication

**Comment by nschonni** [comment]
Looks like there was a dangling reference to Markdownlint, so I removed that for now

**Comment by nschonni** [comment]
looks like CI is happy this time

**Review by OrKoN — APPROVED** [review]

**Pull request merged**
