### PR TITLE
test: update test expectations

### PR DESCRIPTION
**Pull request by OrKoN**

### CODE REVIEW

**Comment by OrKoN** [comment]
@whimboo @juliandescottes I have removed the expectations blocked on the cache behavior but they do not pass yet. Is there anything that has not landed still or is there another issue?

**Comment by OrKoN** [comment]
It looks like it is the CSS caching issue as well?

**Comment by juliandescottes** [comment]
> It looks like it is the CSS caching issue as well?

Yes exactly I need to rebase my PR to update the tests, same issue with the stylesheet cache

**Comment by OrKoN** [comment]
I am not 100% it is about CSS so I marked them as FAIL with a note to investigate

**Comment by juliandescottes** [comment]
The coop font one fails because of a race condition, but I think we should fix it in the test? The others are stylesheet issues, I prepared a PR for this at #12709 but it will probably clash with yours

**Pull request closed without merging**
