### PR TITLE
In page object example

### PR DESCRIPTION
**Pull request by JoelEinbinder**
This example adds a `puppeteer` proxy object into the page.

### CODE REVIEW

**Comment by Garbee** [comment]
While this is super nifty, do you have a use-case for this kind of setup? Flashy but I don't see how it is too useful to developers to include as an example.

**Comment by JoelEinbinder** [comment]
It lets you easily upgrade from a test runner that simply injects javascript into the page. I wrote it for one of my personal projects.

**Comment by aslushnikov** [comment]
Should you rather have this example as a part of a blog post on medium? You would be able to explain the motivation behind it and give a specific practical usecase.

I'd like 'examples' folder to contain practical receipts. We don't have it now, but that might be the ultimate goal.

**Comment by Garbee** [comment]
If it does stay in examples, perhaps a rename to `access-puppeteer-in-page.md` would be better. To more specifically convey the purpose behind the example. `inpageobject.md` is not that descriptive.

I do kind-of agree with this being more of an external blog-post type situation too. I don't feel it would be too common of a thing for developers to do regularly.

**Comment by JoelEinbinder** [comment]
I'm fine with that. I just had some code, figured I would post it.

**Pull request closed without merging**
