### PR TITLE
chore: propagate 'Invalid header' errors

### LINKED ISSUE #5570: request.respond times out when given malformed header with embedded carriage return
I'm scraping a client site to help migrate their content to a new CMS. To avoid stressing the source system, I did a little light caching, saving the previously scraped URL's header and body to my filesystem and intercepting the requests.

I was surprised to discover that some URLs timeout when served from my cache, but not when actually pulled from the source system. I tracked this down to a malformed header being produced by the source system: It contains an embedded carriage return.

Chrome handles this okay when it sees it in the wild. But when puppeteer echoes it back, the navigation times out.

In my actual scraper, I'm just removing the header, which is unnecessary. I've made a minimal test case:

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 2.0.1
* Platform / OS version: Windows 10
* URLs (if applicable): Any
* Node.js version: 12.16.1

**What steps will reproduce the problem?**

Intercept any URL and respond with a broken header that contains an embedded carriage return.

**Test Case**
```min.ts
import puppeteer from 'puppeteer';

const rootUrl = 'http://www.google.com/';

const spider = {
    browser: null as any,
    page: null as any,
    async setup(): Promise<any> {
        this.browser = await puppeteer.launch();
        this.page = await this.browser.newPage();

        this.page.setRequestInterception(true);

        this.page.on('request', (req: puppeteer.Request) => {

            (async (): Promise<any> => {
                const headers = {
                    'x-bogus-header': '1.1\n1.1' // This is the culprit
                };
                const body = "Test";


                await req.respond({
                    status: 200,
                    headers: headers,
                    body: body,
                })

            })();

        });
        await this.page.goto(rootUrl);
    },
    async teardown(): Promise<any> {
        await this.page.close()
        await this.browser.close();

    },
};

async function main(rootUrl: string): Promise<any> {

    await spider.setup();
    await spider.teardown();
}

main(rootUrl).catch(err => {
    console.log(`Top level Error: ${err}`);
    return spider.teardown();
}).then(() => { undefined; });

```
**What is the expected result?**
The intercepted fake response should load in the browser, as it does on the real site.

**What happens instead?**

Navigation times out.

`TimeoutError: Navigation timeout of 30000 ms exceeded`

### LINKED ISSUE #6227: goto timeout when header key inserted during interception contains space or /
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 5.1.0
* Platform / OS version: linux
* URLs (if applicable): any
* Node.js version: 12.16.2 or 10.21.0

**What steps will reproduce the problem?**

simply call this script which sets `HTTP/2 200` as a header during request interception. The problem also happens with `HTTP/1.1 200 OK` as a header. The problem is in the key, not in the empty value. It looks like it doesn't like a `/` or ` ` in the key.

```
'use strict';

const puppeteer = require('puppeteer');
const longjohn = require("longjohn");
longjohn.async_trace_limit = -1;

const URL = "https://www.npmjs.com/package/eslint-config-airbnb-typescript";

async function intercept(page) {
  await page.setRequestInterception(true);
  page.on("request", (request) => {
    if (request.url() === URL) {
      request.respond(
        {
          body: "demo",
          contentType: "text/html",
          headers: { "HTTP/2 200": "" },
          status: 200
        }
      )
    } else if (request.resourceType === "Image") {
      request.abort();
    } else {
      request.continue();
    }
  });
}

(async () => {
  process.on("uncaughtException", (e) => {
    console.error("Unhandled exeption:", e);
    process.exit(1);
  });
  process.on("unhandledRejection", (reason, p) => {
    console.error("Unhandled Rejection at: Promise", p, "reason:", reason);
    process.exit(2);
  });
  const args = [
    "--disable-gpu",
    "--disable-setuid-sandbox",
    "--force-device-scale-factor",
    "--ignore-certificate-errors",
    "--no-sandbox",
  ];
  const options = {
    args,
    headless: true,
    ignoreHTTPSErrors: true,
    dumpio: false,
  };
  const browser = await puppeteer.launch(options);
  const page = await browser.newPage();
  intercept(page);
  const res = await page.goto(URL, { timeout: 30000, waitUntil: "load" });
  console.log("result:", res);
  await page.waitFor(1000);
  const html = await page.content();
  await page.screenshot({ path: "one.png", fullPage: true });
  await page.close();
  await browser.close();
})();
```

**What is the expected result?**

the script should run without an error

**What happens instead?**

the goto timeouts

```
$ npm run node misc/one.js

> demo@1.0.0 node /home/louis/Code/demo
> nodejs "misc/one.js"

Unhandled Rejection at: Promise Promise {
  <rejected> TimeoutError: Navigation timeout of 30000 ms exceeded
      at /home/louis/Code/demo/node_modules/puppeteer/lib/cjs/common/LifecycleWatcher.js:106:111
      at FrameManager.navigateFrame (/home/louis/Code/demo/node_modules/puppeteer/lib/cjs/common/FrameManager.js:88:21)
      at Frame.goto (/home/louis/Code/demo/node_modules/puppeteer/lib/cjs/common/FrameManager.js:405:16)
      at Page.goto (/home/louis/Code/demo/node_modules/puppeteer/lib/cjs/common/Page.js:816:16)
      at /home/louis/Code/demo/misc/one.js:54:15
  ---------------------------------------------
      at /home/louis/Code/demo/misc/one.js:34:11
      at Object.<anonymous> (/home/louis/Code/demo/misc/one.js:61:3)
      at Module._compile (internal/modules/cjs/loader.js:1156:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
      at Module.load (internal/modules/cjs/loader.js:1000:32)
      at Function.Module._load (internal/modules/cjs/loader.js:899:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
      at internal/main/run_main_module.js:18:47 {
    name: 'TimeoutError'
  }
} reason: TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/louis/Code/demo/node_modules/puppeteer/lib/cjs/common/LifecycleWatcher.js:106:111
    at FrameManager.navigateFrame (/home/louis/Code/demo/node_modules/puppeteer/lib/cjs/common/FrameManager.js:88:21)
    at Frame.goto (/home/louis/Code/demo/node_modules/puppeteer/lib/cjs/common/FrameManager.js:405:16)
    at Page.goto (/home/louis/Code/demo/node_modules/puppeteer/lib/cjs/common/Page.js:816:16)
    at /home/louis/Code/demo/misc/one.js:54:15
---------------------------------------------
    at /home/louis/Code/demo/misc/one.js:34:11
    at Object.<anonymous> (/home/louis/Code/demo/misc/one.js:61:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  name: 'TimeoutError'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! demo@1.0.0 node: `nodejs "misc/one.js"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the demo@1.0.0 node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/louis/.npm/_logs/2020-07-16T11_57_17_295Z-debug.log
```

### LINKED ISSUE #6514: Puppeteer hangs after "Invalid header" error is received
### Steps to reproduce

**Tell us about your environment:**
* Puppeteer version: currently puppeteer-core@5.2.1 (but observed on many other versions)
* Platform / OS version: Linux Debian "Buster"
* URLs (if applicable): -
* Node.js version: 12.16

**What steps will reproduce the problem?**
We’ve been noticing that Puppeteer sometimes hangs indefinitely after random commands, without ever triggering a time-out. This has been happening for over 6 months using various versions of Puppeteer.
We’ve enabled logging on the protocol level and noticed that whenever Puppeteer hangs, the last response received from Chrome is an "Invalid header" error:
```
puppeteer:protocol:RECV ◀ {"id":2228,"error":{"code":-32602,"message":"Invalid header"},"sessionId":"164907C6ED3C68C03A3CD77C9B22322E"}
puppeteer:error Error: Protocol error (Fetch.fulfillRequest): Invalid header
    at /home/app/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/home/app/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:16)
    at HTTPRequest.respond (/home/app/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/HTTPRequest.js:283:14)
    at /home/app/app/lib/adapters/base.js:108:21
    at /home/app/app/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map (<anonymous>)
    at Object.emit (/home/app/app/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:43)
    at Page.emit (/home/app/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at /home/app/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:165:100
```
After that, whatever is the next command will hang indefinitely. In the example above, the next call was a `page.$x(…)` call, resulting in the following message sent:
```
puppeteer:protocol:SEND ► {"sessionId":"164907C6ED3C68C03A3CD77C9B22322E","method":"Runtime.callFunctionOn","params":{"functionDeclaration":"(element, expression) => {\n            const document = element.ownerDocument || element;\n            const iterator = document.evaluate(expression, element, null, XPathResult.ORDERED_NODE_ITERATOR_TYPE);\n            const array = [];\n            let item;\n            while ((item = iterator.iterateNext()))\n                array.push(item);\n            return array;\n        }\n//# sourceURL=__puppeteer_evaluation_script__\n","executionContextId":141,"arguments":[{"objectId":"{\"injectedScriptId\":141,\"id\":6}"},{"value":"//h1[contains(text(), \"Kein Suchergebnis\")]"}],"returnByValue":false,"awaitPromise":true,"userGesture":true},"id":2229}
```
After that, Puppeteer hangs indefinitely. But the actual call after the error doesn't seem to matter. We’ve also observed this with many other calls hanging indefinitely.

_Please include code that reproduces the issue._
It’s difficult to reproduce since it usually only occurs after _days_ of running various puppeteer tasks. We use a new puppeteer instance with a new chrome instance for every task, over many days – until one hangs. 

**What is the expected result?**
The call should at least acknowledge that something went wrong and throw/reject after a certain timeout.

**What happens instead?**
The process hangs indefinitely until killed.

### PR DESCRIPTION
**Pull request by MikkelSnitker**
This change allows the use of HttpRequest.respond() with a header object with multiple headers with the same name, by joining the values with a \n char (this is the way headers are stored in a HTTPResponse).

Closes #6514, closes #5570, closes #6227

### CODE REVIEW

**Comment by MikkelSnitker** [comment]
@googlebot I signed it!

**Comment by jackfranklin** [comment]
@MikkelSnitker thanks for this PR. Would you be happy to add a unit test to cover this behaviour?

**Review by jschfflr — CHANGES_REQUESTED** [review]
As @jackfranklin already mentioned: Happy to land this with the according unit test coverage and documentation update!

**Comment by jschfflr** [comment]
@googlebot I consent.

**Comment by jschfflr** [comment]
@MikkelSnitker I added tests for your change but it looks like CDP can't handle multiple headers with the same name. Instead,  I opted to report invalid header values properly. Let me know what you think!

**Review by jschfflr — APPROVED** [review]

**Comment by jschfflr** [comment]
Closes https://github.com/puppeteer/puppeteer/issues/6514, https://github.com/puppeteer/puppeteer/issues/5570, https://github.com/puppeteer/puppeteer/issues/6227 by making sure that the `Invalid header` error is propagated to the user.

**Pull request merged**
