### PR TITLE
param size to 'IO.read' solve problem firefox PDF 

### PR DESCRIPTION
**Pull request by logycware**
problem related to the size of the generated PDF with firefox

doc for IO.read: https://chromedevtools.github.io/devtools-protocol/tot/IO/

### CODE REVIEW

**Comment by jackfranklin** [comment]
@mjzffr @whimboo would one of you mind taking a look? :)

**Comment by mjzffr** [comment]
@logycware Could you provide more context? What issue does this solve? Why 102400? Could you add a Puppeteer unit test that captures the issue?

The IO.read implementation in Firefox sets a [default chunk size](https://searchfox.org/mozilla-central/rev/227f22acef5c4865503bde9f835452bf38332c8e/remote/domains/parent/IO.jsm#99)

**Comment by mjzffr** [comment]
@logycware Oops, I missed #5671, but my other questions still stand. Thanks :)

**Comment by mjzffr** [comment]
I did a bit of digging and found [the source of the problem](https://bugzilla.mozilla.org/show_bug.cgi?id=1632722#c2). We'll push a fix to Firefox and I'll comment on #5671 when that lands so you can try it out.

Thanks for bringing this to my attention. :)

**Pull request closed without merging**
